### ISSUE TITLE
[REQ] SmartSpin2K as smart trainer

### ISSUE THREAD

**Issue by eMadman** [cagnulein/qdomyos-zwift#1080]
V3 of the SmartSpin2K PCB is currently in testing.  The biggest change with V3 is the introduction of a serial data connection that can read sensor data off bikes like the Peloton Bike.  

I realized in my testing last night that the current SS2K integration in QZ requires QZ to be connected to a bluetooth power/cadence sensor.  With this update, that is not possible since the bike itself does not transmit any sensor data over bluetooth.  SS2K is acting as the bluetooth server in this situation.

![image](https://user-images.githubusercontent.com/24726844/207988749-b06832e9-f09c-46f3-a357-30c455c68662.png)

**Comment by cagnulein** [comment]
ok @eMadman should be ok. Try to pull it and you need to enable the new "peloton bike" setting in the SS2K section setting in QZ along with the ss2k combo list there.
Let me know

**Comment by eMadman** [comment]
I don't have a Linux machine or VM available to compile on right now.  I'll install ubuntu on Virtualbox this weekend and see if I can get a build going

**Comment by cagnulein** [comment]
if you I can send you the android or ios build as soon as I will build. Just send me an email as reminder :)

**Comment by cagnulein** [comment]
> One observation: Whenever QZ first detects SS2K, it turns the knob several times to reduce resistance. This behavior may crash the knob.

this is not expected: do you have a debug log?

**Comment by eMadman** [comment]
[debug-Fri_Dec_16_10_54_10_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/10247224/debug-Fri_Dec_16_10_54_10_2022.log)
Here ya go

**Comment by cagnulein** [comment]
got the issue @eMadman 
the movement that you're seeing is about the startup resistance setting in qz. you have 15, and i'm sending to set 15 resistance lvl to the ss2k. you can set it to 1 for example.
also remove the power sensor name (now set also to ss2k)
Let me know

**Comment by eMadman** [comment]
I got a test ride going in a free ride on the bike.  

zero or 1 resistance on the Peloton Bike is approx 15w at 90rpm - QZ does not calculate resistance this low.  I think the lowest is in the 20's.  I also had to set my min brake watts in firmware very low to support this.  There's still plenty of room to turn the knob below zero so it is not a hard endstop.  Log attached:

[debug-Mon_Dec_19_18_47_48_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/10264233/debug-Mon_Dec_19_18_47_48_2022.log)

With my next attempt at testing, I closed out the app and rebooted the SS2K. I wanted to try to start a Peloton PZ ride.  It would detect the SmartSpin2K but it would not make a connection - it stayed in this state for a while.  Rebooted phone, restarted SS2K, restarted QZ - no luck. Log attached

[debug-Mon_Dec_19_19_06_02_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/10264237/debug-Mon_Dec_19_19_06_02_2022.log)

**Comment by cagnulein** [comment]
> zero or 1 resistance on the Peloton Bike is approx 15w at 90rpm - QZ does not calculate resistance this low. I think the lowest is in the 20's. I also had to set my min brake watts in firmware very low to support this. There's still plenty of room to turn the knob below zero so it is not a hard endstop. Log attached:

maybe the perfect solution is sending the resistance level directly on FTMS? are you able to do so?



> With my next attempt at testing, I closed out the app and rebooted the SS2K. I wanted to try to start a Peloton PZ ride. It would detect the SmartSpin2K but it would not make a connection - it stayed in this state for a while. Rebooted phone, restarted SS2K, restarted QZ - no luck. Log attached

fixed thanks! I will send you a new one today!

**Comment by cagnulein** [comment]
@eMadman actually i'm using the FTMS bike module for this implementation. I will create a new module for this and yes, in this way I can read the custom characteristic. How is precise the resistance read from the SS2K? I mean on the peloton bike can you have a 1:1?

**Comment by doudar** [comment]
It is read directly via serial from the bike so it would be the exact same value as displayed on the bike HU

**Comment by cagnulein** [comment]
ok so perfect. Now I have to decide if:
- create a special FTMS bike module, adding the resistance custom characteristic
- using the ss2k module adding the FTMS readings

In order to choose the right path: 
- should I use the custom char or the FTMS one to control the resistance? or is the same?

**Comment by doudar** [comment]
Preferably you would use custom char and directly tell it the steps to use. 

Also to clarify, I'll add another code to the custom char specifically for reading only the Peloton Resistance. It won't be writable.

**Comment by cagnulein** [comment]
> Preferably you would use custom char and directly tell it the steps to use.

aren't the step always the same for all the peloton bike? I suppose they aren't if you're telling this.

> Also to clarify, I'll add another code to the custom char specifically for reading only the Peloton Resistance. It won't be writable.

hah ok, thanks for the clarification. So I will wait for your implementation before doing mine :)

**Comment by doudar** [comment]
@cagnulein  -

With @eMadman 's testing help, I implemented reading the resistance from the Peloton (Flywheel and Echelon as well).

It's being exported via the FTMS characteristic per the spec, just read the bit field.  

Just keep in mind that setting the resistance via FTMS isn't going to work like you expect. I don't have a routine written to determine how many steps are between resistance points for any given bike that this might be placed on. I might do that in the future, but currently it isn't on my timeline. 

So all you'll get from this is (verified accurate) positional feedback from the Peloton. You can then use it to move the knob accurately either by sending the SS2K simulation incline requests via FTMS or using direct stepper motor position manipulation via the custom characteristic.  

This branch is here: https://github.com/doudar/SmartSpin2k/pull/420

You can find more information on the custom characteristic here:
https://github.com/doudar/SmartSpin2k/blob/eaeaf963c7b6985b8e8094f067dc064a1b4c7c69/src/BLE_Server.cpp#L591

**Comment by cagnulein** [comment]
thanks @doudar @eMadman 
So if i understood correctly, the current QZ version that you already have should already works with your branch https://github.com/doudar/SmartSpin2k/pull/420

Because i'm using the ftms bike profile, so it's already reading the resistance level it's available in the bits.
The control, by the other hand, is done by FTMS inclination command, so in a very standard way.

So @eMadman could you try?
The only bug that I can see in the code is that, with the resistance sent from the SS2K by FTMS, i'm not populating the peloton resistance, but this could be easy to fix in case.

Let me know

**Comment by doudar** [comment]
Roberto, From my point of view you are correct! Thank you! Hopefully we get some good test results shortly!

**Comment by cagnulein** [comment]
```
Thu. Dec. 22 10:04:31 2022 1671721471506 Debug: ../src/homeform.cpp void homeform::Minus(const QString &) "Minus" "resistance_minus"
Thu. Dec. 22 10:04:31 2022 1671721471628 Debug: ../src/bluetooth.cpp void bluetooth::debug(const QString &) " >> 11 00 00 ac 0d 00 00 // forceResistance 35"
Thu. Dec. 22 10:04:45 2022 1671721485108 Debug: ../src/homeform.cpp void homeform::Minus(const QString &) "Minus" "resistance_minus"
Thu. Dec. 22 10:04:45 2022 1671721485220 Debug: ../src/bluetooth.cpp void bluetooth::debug(const QString &) " >> 11 00 00 94 11 00 00 // forceResistance 45"
```

qz is working as it should, it's sending the equivalent of 3.5% and 4.5% for resistance 35 and 45 (using the settings)
I guess it's an issue on the SS2K @doudar  ?

**Comment by doudar** [comment]
It will be an hour or so before I can check the logs but If I understand correctly he's pressing the minus button and it went from 35 to 45.

Shouldn't it have gone from 35 to 25?

**Comment by cagnulein** [comment]
@doudar no the resistance was to 46, he pressed the minus and qz sent 4.5% but instead of going down it went up

**Comment by eMadman** [comment]
Reproduced it again with an SS2K log.  
https://pastebin.com/iN13uwLz

And QZ log:
[debug-Thu_Dec_22_11_09_53_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/10288419/debug-Thu_Dec_22_11_09_53_2022.log)

**Comment by doudar** [comment]
Looking at the logs - I see some issues:
**On the SS2K side:**
We start at resistance 13:
`[908026][E](FTMS_SERVER): 00 -> Control Request
	18734	[908190][E](BLE_Common): f1 49 03 33 31 30 d1 f6 <-  |  | PTON[ CD(91.00) PW(22) RS(13) ]`
get a sim mode incline request for 14% grade:
`[908741][E](FTMS_SERVER): 11 00 00 78 05 00 00 -> Sim Mode Incline 14.000000`
which eventually brings the resistance to 45:
'[917414][E](BLE_Common): f1 41 03 39 37 30 d5 f6 <-  |  | PTON[ CD(79.00) PW(146) RS(45) ]'
we then get another sim mode incline request to change the grade to 44%:
`[920808][E](FTMS_SERVER): 11 00 00 30 11 00 00 -> Sim Mode Incline 44.000000`
which eventually brings the resistance to 100 (max):
`[953517][E](BLE_Common): f1 49 03 30 30 31 ce f6 <-  |  | PTON[ CD(0.00) PW(0) RS(100) ]`
Observation - For some reason these incline numbers are way too high. That should be showing a % grade but we're getting much bigger numbers than training apps are sending us. This could be if our FTMS inclination range characteristic is misconfigured and QZ reads it - I'm guessing the apps actually don't. 
**On the QZ side I'm seeing:**
It initialized at the correct current resistance:
`Thu. Dec. 22 11:09:57 2022 Debug: ../src/bluetooth.cpp void bluetooth::debug(const QString &) "Current Resistance: 13"`
We get a user input to increase resistance to 14:
`Thu. Dec. 22 11:10:14 Debug: ../src/homeform.cpp void homeform::Plus(const QString &) "Plus" "resistance_plus"`
`Thu. Dec. 22 11:10:14 Debug: ../src/bluetooth.cpp void bluetooth::debug(const QString &) "writing resistance 14"`
We send SS2K the sim mode incline change for 14% grade:
`Thu. Dec. 22 11:10:14 2022 Debug: ../src/bluetooth.cpp void bluetooth::debug(const QString &) "characteristicWritten 11 00 00 78 05 00 00"`
And we see the Peloton resistance increase to 45 like on the other log.
However I don't see any more user requests to increase the resistance on this log but QZ keeps increasing the simulation inclination target.
I see the next press is:
`Thu. Dec. 22 11:10:27 2022 Debug: ../src/homeform.cpp void homeform::Minus(const QString &) "Minus" "resistance_minus"`
Which QZ then writes as:
 `Thu. Dec. 22 11:10:27 2022 Debug: ../src/bluetooth.cpp void bluetooth::debug(const QString &) "writing resistance 44"`
Because QZ thinks we're currently at 45% incline but we're actually at 14% incline, 45 Peloton resistance. So the resistance increases. 
So I see two issues here. Possibly one with SS2K in that maybe my inclination range characteristic is messing up QZ's decimal place (There's a small chance this might work if QZ had sent 1.4% grade instead of 14% initially. (More on this below.) And another where QZ is treating % grade and Peloton resistance as the same number.
**What I think would work:**
QZ reads the resistance from SS2K. When QZ gets a resistance change from the user, QZ sends FTMS sim mode inclination request of Peloton resistance * a much smaller multiplier (less than .1 See the bottom for an actual number I worked out).  So instead of 14, 1.4 would be more appropriate, 15 would be 1.5 etc. 
Then QZ would monitor the actual resistance and use the sim incline to match the request. So like:
QZ reads bike is at res 14.
User presses res +.
QZ sends incline 1.5.
after seconds, QZ reads bike is at res 16.
qz then says target was 15, actual is 16, send incline of 1.45% 
after seconds, QZ reads bike is at 15 and is happy. 
~
Psudo code: 
static float gradeChangePerResistance = .1; 
int initialResistance = 14;
int targetResistance = 15;
int resistanceAchieved = 16;
int targetDelta = abs(initialResistance - targetResistance); //1 in this case
int actualDelta = abs(initialResistance - resistanceAchieved); //2 in this case
gradeChangePerResistance = (targetDelta/actualDelta) * gradeChangePerResistance; //.05 in this case
~
**Applying this to the numbers we gathered from the logs above:**
~
Psudo code: 
static float gradeChangePerResistance = .1; 
int initialResistance = 13;
int targetResistance = 14;
int resistanceAchieved = 45;
int targetDelta = abs(initialResistance - targetResistance); //1 in this case
int actualDelta = abs(initialResistance - resistanceAchieved); //32 in this case
gradeChangePerResistance = (targetDelta/actualDelta) *  gradeChangePerResistance; //**.03125 in this case**
re-send FTMS sim Incline target of (targetResistance * gradeChangePerResistance) // .4375 in this case
~

**Comment by cagnulein** [comment]
yes actually i'm doing 

resistance request  * 100

so it makes sense what you are saying. this is applied only when you're changing the resistance from the tiles and only for ftms bikes.

so i guess i should easily add some settings here to let you configure this

**Comment by cagnulein** [comment]
@eMadman version 2.12.24 online
what I did:
- now the resistance that you requested from the tile will be
- multiplied for the zwift resistance gain (default 1)
- added with the zwift resistance offset (default 4)
- divided by 10 and used as inclination

so if you set the resistance 20 with the default settings, you will have a inclination request of 2.4% to SS2K.

Let me know if it's better now

**Comment by eMadman** [comment]
Hmm.  This seems to be inconsistent.  Pressing + button does increase resistance but it's not consistent.  Pressing - doesn't seem to respond.  I tried the gears tile as well

SS2K Log: https://pastebin.com/LpnEc7Fp

QZ Log: [debug-Fri_Dec_23_10_40_53_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/10296062/debug-Fri_Dec_23_10_40_53_2022.log)

**Comment by cagnulein** [comment]
ok thanks @eMadman i will check out, for me today and tomorrow are travel day so i will check them for xmas day probably 

Merry Christmas both guys!

**Comment by eMadman** [comment]
> ok thanks @eMadman i will check out, for me today and tomorrow are travel day so i will check them for xmas day probably 
> 
> Merry Christmas both guys!

No rush at all! Merry Christmas to you too!

**Comment by cagnulein** [comment]
@eMadman checked the log, could you try to put the zwift resistance offset to 0 instead of 1?

**Comment by eMadman** [comment]
Log files attached.  It stops shifting after 1 click of the resistance tile.
[debug-Thu_Dec_29_11_09_03_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/10324948/debug-Thu_Dec_29_11_09_03_2022.log)

[ss2k log.txt.txt](https://github.com/cagnulein/qdomyos-zwift/files/10324949/ss2k.log.txt.txt)

**Comment by eMadman** [comment]
looks like the incline is being passed but its not turning the knob enough to be noticeable.  I increased the incline multiplier in SS2K to exaggerate the effect.  I can see it responding to shifts until a certain point.  Look through the logs where I click the resistance + button 7+ times - those had no effect on incline
[debug-Fri_Dec_30_09_07_53_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/10325058/debug-Fri_Dec_30_09_07_53_2022.log)

[debug-Fri_Dec_30_09_07_53_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/10325061/debug-Fri_Dec_30_09_07_53_2022.log)

**Comment by cagnulein** [comment]
thanks @eMadman it seems fine from the QZ point of view, i'm using the current resistance from SS2K to decide which inclination I have to send. In the last log the resistance stay to 35...maybe a single 0.1% of inclination is not enough? maybe you need to use a zwift resistance gain of 2? @doudar what do you think?

**Comment by doudar** [comment]
> thanks @eMadman it seems fine from the QZ point of view, i'm using the current resistance from SS2K to decide which inclination I have to send. In the last log the resistance stay to 35...maybe a single 0.1% of inclination is not enough? maybe you need to use a zwift resistance gain of 2? @doudar what do you think?

I don't know. I'm thinking it might just be best if I expand resistance control FTMS mode where if SS2K has resistance feedback from a trainer it will then automatically seek to the resistance level commanded by the FTMS client. Instead of trying to do this via incline mode.

**Comment by cagnulein** [comment]
yes i guess it will be perfect solution

**Comment by doudar** [comment]
Okay - I'll get to work on it if you want to change things on your end.

*----------------------*
*Anthony Doud*

**Comment by cagnulein** [comment]
ok i will do this tomorrow

**Comment by doudar** [comment]
First round is done on my end. Excited to see the crash logs tomorrow from @eMadman 😅

**Comment by cagnulein** [comment]
done, i will send the update later today. Version 2.12.34

**Comment by eMadman** [comment]
Testing the new builds for both QZ and SS2K.  This is looking pretty good.  QZ calls for a resistance change.  SS2K is responding.  Some overshooting on the SS2K side but it finds the target eventually.

Latest SS2K build helped improve the latency I was seeing between the bike and apps

SS2K log has more test data in it: [Custom UDP Receiver (Port 10000).csv](https://github.com/cagnulein/qdomyos-zwift/files/10338052/Custom.UDP.Receiver.Port.10000.csv)

QZ Log - this QZ session is in the 2nd half of the SS2K log: [debug-Tue_Jan_3_10_56_43_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/10338057/debug-Tue_Jan_3_10_56_43_2023.log)

Video because it's really cool! https://photos.app.goo.gl/dh1WPU3TmpRU6j799

**Comment by eMadman** [comment]
Just finished one. Qz log from a Power zone workout attached.  It went flawlessly.

I forgot to record the ss2k log here
[debug-Tue_Jan_3_11_23_39_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/10338730/debug-Tue_Jan_3_11_23_39_2023.log)

**Comment by eMadman** [comment]
Latest test on the [FTMS_Resistance](https://github.com/doudar/SmartSpin2k/pull/420) branch of SS2K worked really well with QZ & Peloton (Low impact resistance ride))

It landed on resistance targets almost immediately each time changes were called.  Failed midway through but I'm confident that that was my fault - switched focus away from QZ to DM you & @doudar .  I think QZ lost the session 😅

I should do an erg ride as a final test but this is feeling really good.
[debug-Sun_Jan_22_11_15_13_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/10474949/debug-Sun_Jan_22_11_15_13_2023.log)

**Comment by eMadman** [comment]
Erg test ride using latest develop build of SS2K was completely uneventful... no surprises, it stayed on target resistance throughout the ride.  The best kind of test ride!  Log file attached.

![Tue  Jan  31 18_38_19 2023_power](https://user-images.githubusercontent.com/24726844/215909455-20bb4e02-e925-4e97-a7d6-9fbbf22a1226.png)
![Tue  Jan  31 18_38_20 2023_speedInclination](https://user-images.githubusercontent.com/24726844/215909470-4708bc91-c17e-4ff2-8cc1-cde88b42ca66.png)

[debug-Tue_Jan_31_18_06_07_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/10551921/debug-Tue_Jan_31_18_06_07_2023.log)
