### ISSUE TITLE
Zwift Runpod

### ISSUE THREAD

**Issue by cagnulein** [cagnulein/qdomyos-zwift#1097]
Should I open a new issue for Rouvy?  I enabled the 'bike power sensor' in experimental settings on the Note 8 (now named Waho), but Rouvy still wont connect.  

Also, on my regular phone (a Note 20 now named Bike), I can see the Zwift footpod in qz but the bluetooth indicator flashes, and I dont get any tiles (I'm on a profile called Run).  (And The Zwift footpod is selected under Manual Devices in Advanced settings).   So neither Zwift or Rouvy will see the footpod. I've rebooted the Note 20 and no other bluetooth devices are active, so the footpod is not connected to anything else.

Note 8 Debug 
[debug-Mon_Dec_26_14_25_30_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/10304685/debug-Mon_Dec_26_14_25_30_2022.log)

Note 20 Debug
[debug-Mon_Dec_26_15_01_29_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/10304686/debug-Mon_Dec_26_15_01_29_2022.log)
![Screenshot_20221226_144706](https://user-images.githubusercontent.com/83240285/209580442-b1a406f3-ee46-47d6-adcc-299c791e8b18.jpg)

_Originally posted by @jra650 in https://github.com/cagnulein/qdomyos-zwift/issues/1085#issuecomment-1365442323_

**Comment by jra650** [comment]
Roberto – No.  I discontinued my Zwift subscription and because Rouvy removed its running component, I no longer use QZ with run based applications.  

 

However, I still have a Zwift RunPod and can sign up for a trial Zwift subscription if you need the RunPod tested with the latest version of QZ. 

 

All other sensors I’m currently using have been working well with the updated QZ and I haven’t gotten a QZ crash on Rouvy in over 1 year.  Thanks for your great work! - James

**Comment by cagnulein** [comment]
ok no problem, thanks! already got my answers :)
