### ISSUE TITLE
[BUG] The software is unstable working.

### ISSUE THREAD

**Issue by TanaevAK** [cagnulein/qdomyos-zwift#1166]
The average time of work in my case is around 20-25 min, and after that the app crashes.
 I use an iPad Pro (A1934) with iPadOS 16.2 (20C65) and iPhone 14 (A2882) with iOS 16.2(20C65)

**Append a debug log**
[debug-Пн_янв__16_18_15_04_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/10433756/debug-._.__16_18_15_04_2023.log)

**Comment by cagnulein** [comment]
@TanaevAK the problem is simple from your log:

the wifi connection to your bike is dropping

`Пн янв. 16 18:35:10 2023 1673879710381 Debug: /Users/cagnulein/qdomyos-zwift/src/proformwifibike.cpp auto proformwifibike::proformwifibike(bool, bool, uint8_t, double)::(anonymous class)::operator()() const disconnected!`

check the wifi icon on your bike, wifi icon on your phone and also check your access point. It's everything releated to this

Let me know

**Comment by TanaevAK** [comment]
This is a log for video I sent you yesterday in Facebook 
[debug-Чт_янв__19_18_24_32_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/10465077/debug-._.__19_18_24_32_2023.log)

**Comment by cagnulein** [comment]
@TanaevAK the ip is not correct, there is no answer from the bike. Please check the ip address of the bike
