### ISSUE TITLE
[BUG] What previously worked no longer works! I have android app, iconsole bike and IOS Zwift all connected but it's not registering any bike data, ie. no watts...

### ISSUE THREAD

**Issue by lowebo2k** [cagnulein/qdomyos-zwift#1377]
[debug-Fri_Mar_24_15_22_46_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/11063396/debug-Fri_Mar_24_15_22_46_2023.log)

**Comment by cagnulein** [comment]
@lowebo2k I didn't change nothing in the code about iconsole bike. Since when you have this issue?

**Comment by lowebo2k** [comment]
Since the last month.

**Comment by cagnulein** [comment]
checking the log the bike stops to answer to qz after just 1 second. Are you able to check if this bike still work with kinomap for example? @lowebo2k

**Comment by lowebo2k** [comment]
Yes works fine with Kinomap

**Comment by cagnulein** [comment]
@lowebo2k does the bike received a firmware upgrade?

I double checked the code and it's still the same since november 2022. So in order to fully understand the cause I need a hci snoof from kinomap following this https://github.com/cagnulein/qdomyos-zwift/blob/master/docs/20_supported_devices_and_applications.md#android-device

Let me know!

**Comment by cagnulein** [comment]
@lowebo2k any news?

**Comment by lowebo2k** [comment]
Sorry no, I've given up and will use Kinomap instead.

Cheers anyway.

**Comment by cagnulein** [comment]
ok i'm here if you will change your mind. For sure it's an easy one to fix
