### ISSUE TITLE
[BUG] Cadence in Wahoo Direct Connect mode

### ISSUE THREAD

**Issue by smulrine** [cagnulein/qdomyos-zwift#1396]
Is cadence supposed to work in Zwift when using direct connect mode? The power reading from my Tacx Neo seems OK but cadence is all over the place, from 1 rpm to 192 when I tested it this evening. This was on a Radxa Zero running the latest version of QZ on Manjaro Linux but I saw the same thing months ago on a Banana Pi M2 Zero. Cadence over Bluetooth is fine.

**Comment by cagnulein** [comment]
yes @smulrine it has to work but i guess it's more an issue with the tacx #878 

did you see the right cadence on the qz tile?

**Comment by smulrine** [comment]
Yes, cadence in the QZ tile looks fine and it also works fine when I pair Zwift with the Bluetooth qdomyos-bridge device

**Comment by cagnulein** [comment]
ok so it has to work because it's the same setup that i'm using on my bike. so in order to summarize:

- cadence is getting ok from the bike
- qz to zwift over bluetooth sends all the metrics fine
- qz to zwift over wi-fi sends the cadence wrong?

if so, try to send me a debug log and i can check it

**Comment by smulrine** [comment]
That's correct - log file attached. It ends suddenly because the process terminated with a segmentation fault. The Radxa Zero may still not be reliable (at least not without an antenna) but I did compile the app in an SSH session without any trouble, and the cadence sent over wifi by a Banana Pi M2 Zero showed exactly the same behaviour.
[qz-rz.log](https://github.com/cagnulein/qdomyos-zwift/files/11163363/qz-rz.log)

**Comment by cagnulein** [comment]
@smulrine in this log I don't see any metrics from the tacx neo. Also you enabled the rizer, i suggest to disable it because it could be the issue of your segmentation fault (you're the first one that is trying the rizer implementation I guess).
So repeat the log in order to have some metrics on it
Thanks

**Comment by smulrine** [comment]
How does this look? Rizer disabled, no segmentation fault (although I only rode for about 30 seconds), cadence all over the place but mostly 1rpm
[debug-Mon_Apr_10_20_16_44_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/11193292/debug-Mon_Apr_10_20_16_44_2023.log)

**Comment by cagnulein** [comment]
@smulrine I guess I fixed it! Pull and build this branch and let me know https://github.com/cagnulein/qdomyos-zwift/pull/1406

**Comment by smulrine** [comment]
Thanks, that seems to have done the trick!

**Comment by cagnulein** [comment]
Great! I'm merging this! Do you need some other tests or you are confident bout this?

**Comment by smulrine** [comment]
Tried it for a couple of minutes using both Bluetooth and wi-fi connections, cadence looked fine so I'm confident it's fixed.
