### ISSUE TITLE
Question: Is there any way to get an official APK other than from Google Play?

### ISSUE THREAD

**Issue by rafael-trevisan** [cagnulein/qdomyos-zwift#142]
Hi, I'd love to buy the app from  the Google Play but I am not in the Google ecosystem and my bike's tablet doesn't have the Google Play available. is there any plan or way to sponsor this repo or its authors and get an official APK so I can install in my tablet here?

Actually, have you @cagnulein thought to setup the GitHub sponsorship program and gets sponsored monthly in exchange of providing an APK updated every month? I'd be happy to subscribe in a monthly sponsorship here if you were to offer this option.

Great work with the app!

**Comment by cagnulein** [comment]
Hi @rafael-trevisan thanks for the idea.
My idea behind my project is:
who is enough "nerd" to compile itself the app, it can use it for free, the rest of them should pay a little for my work (and support of course!) :)

But yes, i understood your request.
Maybe i can create a sort of mailing list or whatever, in order to share the APK.
I will think about it.
In the meanwhile, just write me at roberto.viola83@gmail.com and we will see what i can do ;)

**Comment by rafael-trevisan** [comment]
Hi @cagnulein,

Yeah, I kinda thought of cloning the repo and building and etc... I even managed to enable the "Developer Mode" in the funny Android tablet, but with so much going on I thought it'd be easier if I could sponsor the repo ;)

I will reach out to you. In the meantime, enjoy the coffee ☕️

**Comment by cagnulein** [comment]
@rafael-trevisan thanks! i really appreciate that! ;)
Contact me as soon you're ready ;)
