### ISSUE TITLE
[REQ] QUIT button on Android OS

### ISSUE THREAD

**Issue by gadi247** [cagnulein/qdomyos-zwift#1456]
**Is your feature request related to a problem? Please describe.**
Latest version of (BETA) app loses the QUIT button in the Side/Settings Menu - want a way to QUIT after workout

**Describe the solution you'd like**

Latest version of (BETA) app loses the QUIT button in the Side/Settings Menu - want a way to QUIT after workout

**Describe alternatives you've considered**

**Additional context**

**Comment by cagnulein** [comment]
checked the code. I removed it because for small android screen, the list
was too long and I thought that since the quit action is just the swipe it
could be useless. What do you think?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 10 mag 2023 alle ore 20:24 gadi247 ***@***.***>
ha scritto:

**Comment by gadi247** [comment]
if swiping closes out the app fully then I guess no need but an EXIT button
is nice to have
