### ISSUE TITLE
WalkingPad X21 new version

### ISSUE THREAD

**Issue by cagnulein** [cagnulein/qdomyos-zwift#1473]
![image](https://github.com/cagnulein/qdomyos-zwift/assets/48216/d048c299-302d-4285-967a-f9438143c97c)

**Comment by cagnulein** [comment]
[debug-Sat_May_20_16_27_59_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/11522837/debug-Sat_May_20_16_27_59_2023.log)
[debug-Sat_May_20_16_28_47_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/11522838/debug-Sat_May_20_16_28_47_2023.log)

**Comment by cagnulein** [comment]
@d3m3vilurr another key I guess if you want to have fun with :)

**Comment by d3m3vilurr** [comment]
probably, `iaCw4FGHIJqLhN+P9RVTU/WcY6ObDdefgEZjklmnopQrsBuvMxXz1yA2t5078KS3=` is the key.
(swap `Z` <-> `i` from original table)

**Comment by d3m3vilurr** [comment]
an original table is `ZaCw4FGHIJqLhN+P9RVTU/WcY6ObDdefgEijklmnopQrsBuvMxXz1yA2t5078KS3=` (i couldn't remember maybe `=` is not existed in the table. i just added it for easily decrypting)

so we can compare an expected result with original key and received key with unknown key.
usually, just 1 position could be swapped.

the problem is we don't know what message is broke.

here is sending / receiving flows
```
1) most devices it will return `shake 00`
-> shake
<- shake 00

2) here is two cases
-> net
# my case
<- net cloud
# another cases
<- net unprov

3) dn number could be depended by devices
-> get_dn
# my case
<- get_dn 100801210820000007 
# another case of this debug
<- get_dn 3

4) pk number could be also depended by devices
-> get_pk
# my case
<- get_pk a1hiSOeUajy
# another case of this debug
<- get_pk 3

5) timestamp could be current time
-> timestamp 1629831426
<- timestamp 0

6) version value is related by device
-> version
# my case
<- version 0014
# another case of this log
<- version 0006

7) initialized getting properties. this command only callable after handshake (~ after sending `get_pk` or after sending `version`)
-> servers getProp 1 3 7 8 9 16 17 18 19 21 22 23 24 31
# i'm not sure but this first return could be always same
<- servers 0 
# second / third return could be depended by current device conditions
# for example `ControlMode` was `1` in this log
<- props ControlMode 2 ChildLockSwitch 0 runState 0 handrail 0 MaxW 6.0 Max 12.0 StartSpeed 2.0 VelocitySensitivity 2 PanelDisplay 7
<- props ConSpMode 0 initial 4 mcu_version "0001" unit 0

8) now can send command
-> props ControlMode 1
# then we can feed the response of status of the device.
<-  ...
```

so a brute force the key is required cross checking receiving data with original table :)
for example, i compared `props netled 0 ControlMode 1` then full check with `props netled 0 ControlMode 1 runState 0 CurrentSpeed 0.0 Max 12.0 unit 0`.
then try to decrypt `64 6d 2f 58 44 41 6c 76 62 5a 69 4d 68 77 69 41 77 39 3d 3d 0d` (`version 0006`)

**Comment by cagnulein** [comment]
> iaCw4FGHIJqLhN+P9RVTU/WcY6ObDdefgEZjklmnopQrsBuvMxXz1yA2t5078KS3=

it worked! let me try with the user!

**Comment by cagnulein** [comment]
worked! thanks again @d3m3vilurr !
