### ISSUE TITLE
[REQ] Support Lifespan Fitness Treadmill

### ISSUE THREAD

**Issue by wtafe** [cagnulein/qdomyos-zwift#1689]
Attached is the requested btsnoop_hci.log

I hope it got the right data during my log collection.

App supports Steps, Speed, Calories, Distance. It might be my setup, but the mph/kph seemed wildly inaccurate from phone app to treadmill console (about 1/2 most of the time)

[btsnoop_hci.log](https://github.com/cagnulein/qdomyos-zwift/files/12834643/btsnoop_hci.log)

**Comment by cagnulein** [comment]
thanks i will check it asap

Il giorno ven 6 ott 2023 alle 21:05 wtafe ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
I started the implementation: which speed did you keep in this workout? do you have a chart of this workout so I can parse the data correctly? Let me know @wtafe

**Comment by wtafe** [comment]
Let me track it a bit better and resubmit. I recall increasing the speed  gradually.

**Comment by cagnulein** [comment]
ok thanks, the treadmill sends 7 different metrics in 7 different frames so
i have to understand which one is the speed, inclination, step, distance....

Il giorno lun 9 ott 2023 alle 20:09 wtafe ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
@wtafe any news?

**Comment by dkozel** [comment]
@cagnulein Hello. I have a Lifespan TR1200 and have been able to capture a Bluetooth HCI log from my phone. I've read through the log in Wireshark and I couldn't find any obvious signs of the metrics transferring, but I've never worked with Bluetooth before. Are you interested in continuing to add support for this treadmill? If so I can capture a log while specifically controlling speed and steps separately.

**Comment by cagnulein** [comment]
Sure! Share the logs

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 17 gen 2025 alle 11:17 Derek Kozel ***@***.***>
ha scritto:

**Comment by dkozel** [comment]
Great, thanks for looking at it!

The treadmill started with 1 step already recorded and a speed of 0.7 km/h. I ramped the speed slowly up to 2.0 km/h, then started walking. Here's a video of the app through (most) of the bluetooth session. I don't have a perfect workflow for the bluetooth capture, happy to make more short captures at different states if that's clearer.

https://youtube.com/shorts/-_g6dx5Q9KM

I believe the Bluetooth capture includes a short section at the start where I was setting up the treadmill, then a much longer session which is the actual test run. 
[20250117-speed-07-to-20-btsnoop_hci.log](https://github.com/user-attachments/files/18453554/20250117-speed-07-to-20-btsnoop_hci.log)

The physical console shows Time, Step/Level, Calories, Distance, Speed, and Weight. This model has no incline control.

Happy to help in any ways.

**Comment by cagnulein** [comment]
@dkozel good news! i guess i already started and possible have a working solution #3021 
are you on android or ios?

**Comment by dkozel** [comment]
I'm on Android.

**Comment by cagnulein** [comment]
Ok so you can try the nightly build from here https://github.com/cagnulein/qdomyos-zwift/releases/download/nightly/android-debug.apk


Google is very slow in these days, reviewing the app on the store, even the beta ones. For this reason, in order to check right now if the patch that I did is right, you can use the android build in the link (check at the bottom of the page in about 1 hour). In order to test it you need first to remove the current QZ version on your phone, install the one that you downloaded.
This version is a 15 minutes trial (you can restart it as many times as you want) and I can unlock it if you want, send me an email to roberto.viola83@gmail.com mentioning this ticket and that you are on android.
Let me know if you have any questions
