### ISSUE TITLE
[BUG] Large Calorie difference between QZ and Zwift

### ISSUE THREAD

**Issue by hortocam** [cagnulein/qdomyos-zwift#1696]
**Describe the bug**
Large difference between QZ calorie count and what Zwift & Bike are calculating.  

Main concern is that if QZ is calculating much higher, this is the data that is going to Apple Health and it makes my Active Energy counts way higher than reality.  

Secondary concern is that Apple Watch is counting active energy at the same time a workout is going on.  I am using the QZ app from my watch for HRM.  

Combined together, my active energy is overstated so I cannot rely on what I see it Apple Health or the Fitness app.  

**Example**
I am 52 yo male.  I weigh 315 pounds.  My weight is set to 315 in Zwift and 317 in QZ.
FTP: 200

I did a 7mi ride this morning.  QZ calculated 715 calories.  Zwift showed 315.  

You can see from the Apple Health screenshot that it recorded 715 calories from QZ at 10:54am.  But prior to that (it goes back to the time I started the ride) my watch is also tracking active calories at sub-minute intervals.

In the overall move calories it seems to be adding these together.  
[debug-Tue_Oct_10_09_36_46_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12859965/debug-Tue_Oct_10_09_36_46_2023.log)

**Expected behavior**
Relative parity between calorie calculations on Bike / Zwift / QZ.

**Screenshots**
![IMG_1810](https://github.com/cagnulein/qdomyos-zwift/assets/8212282/446bc3b5-76f5-49f0-a513-838e666d7570)

![IMG_1807](https://github.com/cagnulein/qdomyos-zwift/assets/8212282/7ec79a8f-e4ea-4b2c-b5e0-e0abf37ba1e0)

![IMG_1808](https://github.com/cagnulein/qdomyos-zwift/assets/8212282/85f7f4bb-103d-483d-9b5b-3f56a6b3aea4)

**Smartphone (please complete the following information):**

 - Device: [iPhone13 ProMax]
 - OS: [iOS 17]

**Append a debug log**
Log attached from the morning ride.

**Comment by cagnulein** [comment]
thanks i will check it tomorrow so i will do a single release in case i
will find something

Il giorno mar 10 ott 2023 alle 19:08 Cameron Horton <
***@***.***> ha scritto:

**Comment by cagnulein** [comment]
@hortocam checking with an external tool that have a similar formula looks ok the QZ result.

![image](https://github.com/cagnulein/qdomyos-zwift/assets/48216/225bcd99-c4be-47d6-90c0-7f70c54a1ce7)

of course, as I said by email, there are a lot of different algorithm that are available to calculate the calories. For sure zwift is using a different one.

So let's think about a possible solution for you (if you don't like the QZ result):
- I can add a classic calories gain and calories offset so you can set for example the calories gain to 0.5 in order to have a similar value to Zwift.
- We can search other formulas for KCAL, and we can switch between the original one and the new one with a setting

What do you think?

For the AW issue, I'm checking and I will post here my findings.

Thanks for feedback!

**Comment by cagnulein** [comment]
ok I have also already the answer for the AW thing.
AW is using the most priority app for the KCAL counts if there are multiples. You can set QZ or Apple Calories from this menu.
I checked on my today's workout, and only the QZ ones are counted

![image](https://github.com/cagnulein/qdomyos-zwift/assets/48216/40bcbfb2-f980-4632-9887-7e8b45c324d4)

**Comment by cagnulein** [comment]
![image](https://github.com/cagnulein/qdomyos-zwift/assets/48216/6d99316c-bd76-456c-a128-6b0f59a44789)

1300kcal today

where 1000kcal from my indoor session

![image](https://github.com/cagnulein/qdomyos-zwift/assets/48216/49b24a0c-93e4-4326-842d-cb4a3063112b)

140kcal from my outdoor one
![image](https://github.com/cagnulein/qdomyos-zwift/assets/48216/6b2b6379-5411-4f2e-bc16-c6fdc5cf77bc)

the rest 150kcal is me walking into the office :) let me know your thoughts

**Comment by cagnulein** [comment]
@hortocam are we good with this?
