### ISSUE TITLE
[BUG] Can't control the speed and incline from Technogym MyRun

### ISSUE THREAD

**Issue by alkaraschu** [cagnulein/qdomyos-zwift#1737]
**Describe the bug**
Can't control the incline & speed from treadmill MyRun (Technogym). The MyRun is found by BLE and is showing the speed & incline on the tiles but can't increase/decrease by hitting +/-.

**Expected behavior**
Controllable speed & incline by the app and automatic control by repeating a run with gpx-file

**Smartphone (please complete the following information):**
 - Device: Ipad & Iphone
 - OS: iOS Version 17

**Append a debug log** / is attached
[debug-Sa__Okt__28_13_53_57_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13195803/debug-Sa__Okt__28_13_53_57_2023.log)

**Comment by cagnulein** [comment]
thanks, i will check it asap

Il giorno sab 28 ott 2023 alle 14:48 alkaraschu ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
@alkaraschu log checked. The treadmill doesn't show the attribute to control the incline/speed. I guess it's because this firmware version is locked. Could you please ask to technogym if your treadmill can have a newer version? I know Technogym very well (an Italian company as me :) ) and they usually provide a solution for their customer quickly.
If you want you could also put me in CC with them.
Let me know!

**Comment by alkaraschu** [comment]
I will do😀 What is your Email?

**Comment by cagnulein** [comment]
***@***.***

Il giorno lun 30 ott 2023 alle 09:45 alkaraschu ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
roberto.viola83@gmail.com

**Comment by cagnulein** [comment]
I'm following this by email
