### ISSUE TITLE
Stryd power + Inclination power from the treadmill

### ISSUE THREAD

**Issue by cagnulein** [cagnulein/qdomyos-zwift#1741]
QZ is now getting power from stryd pod when using a Horizon 7.8AT treadmill. 

**Nice to have:** I also noticed that when using an incline on the treadmill, QZ continues to display same power as if the incline was still 0%, probably is because the **client** ( the device where the power is being recorded) is the one responsible for applying the power gain to the data and not the stryd pod itself ( probably the stryd pod is just sending the raw power). 

PS when I say "client" I am using the stryd pod app on a garmin fenix 7x watch, and in there I specify the incline so the power changes on the watch ... I can simply change the power gain on the QZ app to match the power I am seeing on the watch ( I've change the power live and it changes nicely). It would be ideal ( not needed ) to have some preset power gains based on the incline that the treadmill is reporting.

Thank you for all the work you do, I did not expect this level of support!

_Originally posted by @taxi333 in https://github.com/cagnulein/qdomyos-zwift/issues/1729#issuecomment-1783437146_

**Comment by cagnulein** [comment]
@taxi333 done! it will be in the 2.16.21 !

**Comment by taxi333** [comment]
thank you! I’m looking forward to testing this feature

**Comment by taxi333** [comment]
@cagnulein not sure if this is related but on version 656 the qz app read from stryd normally and I can applied a gain to the watt to match the stryd watts when on an incline, while keeping incline constant if I increase my speed, the watts on qz app no longer match the stryd watts and I have to apply a new gain … On version 654 while keeping incline constant and watts gain constant, the qz app match (+/- 2%) what stryd was showing …I’ll check the code tomorrow to see if I can spot what changed  from version 654 to 656 that is producing this new behavior … I prefer 654 because I can set the gain and forget about it as long as I maintain the same incline. ( thank you for reading, I will become a patron supporter 😂)

**Comment by cagnulein** [comment]
@taxi333 what i did in the last version, in order to accommodate this request, is to add to the inclination value to the watt read from the stryd.

probably the gain is applied to the sum not the raw value itself

so this what causing your issue i guess
