### ISSUE TITLE
ERG modefor Toorx SRX 3500

### ISSUE THREAD

**Issue by diditje007** [cagnulein/qdomyos-zwift#1999]
ERG mode is not supported for the Toorx SRX 3500 bike, so I created a power table collecting power from the bike. 

[wattage toorx 3500.ods](https://github.com/cagnulein/qdomyos-zwift/files/13932425/wattage.toorx.3500.ods)
[wattage toorx 3500.xlsx](https://github.com/cagnulein/qdomyos-zwift/files/13932426/wattage.toorx.3500.xlsx)

Can this be used to add ERG support for this bike?

Thank you! 

Let me know if I can do anything else to help

**Comment by cagnulein** [comment]
Thanks I will try to do it asap
Are you on android?

**Comment by diditje007** [comment]
Yes, am on android. Thank you very much!

**Comment by cagnulein** [comment]
@diditje007 could you please attach a debug log of your current setup? so I can add it to the right bike profile. Thanks

**Comment by cagnulein** [comment]
thanks I will check in the next days!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 15 gen 2024 alle ore 16:35 diditje007 <
***@***.***> ha scritto:

**Comment by cagnulein** [comment]
chatgpt extract the power formula

https://chat.openai.com/share/42db1717-01c6-4bf8-856b-fb8b190f90a8

`P=37.069−1.483×cadence−4.942×resistance+0.023×cadence 2 +0.336×cadence×resistance−0.036×resistance 2`

```
double calculatePower(double resistance, double cadence) {
    double P;
    P = 37.069 
        - 1.483 * cadence 
        - 4.942 * resistance 
        + 0.023 * cadence * cadence 
        + 0.336 * cadence * resistance 
        - 0.036 * resistance * resistance;

    return P;
}
```

**Comment by cagnulein** [comment]
@diditje007 done! https://github.com/cagnulein/qdomyos-zwift/actions/runs/7539027737

Google is very slow in these days, reviewing the app on the store, even the beta ones. For this reason, in order to check right now if the patch that I did is right, you can use the android build in the link (check at the bottom of the page in about 1 hour). In order to test it you need first to remove the current QZ version on your phone, install the one that you downloaded.
This version is a 15 minutes trial (you can restart it as many times as you want) and I can unlock it if you want, send me an email to roberto.viola83@gmail.com mentioning this ticket and that you are on android.
Let me know if you have any questions

**Comment by cagnulein** [comment]
@diditje007 any news?

**Comment by cagnulein** [comment]
ok if you want I can check a debug log in case

**Comment by cagnulein** [comment]
@diditje007 due to https://github.com/cagnulein/qdomyos-zwift/discussions/2138 I have to add a new setting to enable this mode. You will find under the the iconsole setting
