### ISSUE TITLE
ProForm 505 CST Treadmill - Speed and Incline Control

### ISSUE THREAD

**Issue by rjkibler** [cagnulein/qdomyos-zwift#2032]
**Describe the bug**
Getting treadmill support for speed and incline control on ProForm 505 CST Treadmill. 

**To Reproduce**
Steps completed on treadmill while iFit recording. 
1. Increase speed
2. Increase incline

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Pixel 6
 - OS: Android
 - Version 14

**Append a debug log**
[btsnoop_hci.log](https://github.com/cagnulein/qdomyos-zwift/files/14011066/btsnoop_hci.log)

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
thanks I will add it ASAP

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 22 gen 2024 alle ore 15:07 Ryan Kibler <
***@***.***> ha scritto:

**Comment by cagnulein** [comment]
[formatted_hex_arrays (1).txt](https://github.com/cagnulein/qdomyos-zwift/files/14012408/formatted_hex_arrays.1.txt)
ok these are the frames that I have to add

**Comment by rjkibler** [comment]
Hi, Roberto! Let me know if there's something else you're needing from me! 

Best, 
Ryan

**Comment by cagnulein** [comment]
yes i will let you know when i will be ready to test it!

**Comment by cagnulein** [comment]
@rjkibler done!
i added a new setting in the proform treadmill section with the name of yours. disable the others
In the hci snoof i didn't see any speed or incline changes, anyway i used the standard profile, let's see if it's right, otherwise you will need to collect another one

https://github.com/cagnulein/qdomyos-zwift/actions/runs/7641092713

Google is very slow in these days, reviewing the app on the store, even the beta ones. For this reason, in order to check right now if the patch that I did is right, you can use the android build in the link (check at the bottom of the page in about 1 hour). In order to test it you need first to remove the current QZ version on your phone, install the one that you downloaded.
This version is a 15 minutes trial (you can restart it as many times as you want) and I can unlock it if you want, send me an email to roberto.viola83@gmail.com mentioning this ticket and that you are on android.
Let me know if you have any questions

**Comment by rjkibler** [comment]
Would you be able to describe what I need to do to be able to use the
android build that you mentioned?

The attached screenshot is what I see from that link.

Is it the "fdroid-android-trial" file? Do I need to download that somehow?
I might need to get on the GitHub app.

Thanks,
Ryan

**Comment by cagnulein** [comment]
i can't see the screenshot, you have to send it on github directly.
yes you need to download that file. you can do only if you are logged in

**Comment by rjkibler** [comment]
Hi, Roberto! 

Great news. The controls in the app worked for my treadmill!

I am going to work on getting it set up with Zwift this week! Thanks for all your help and quick response to get this working. I really appreciate it. 

Best, 
Ryan

**Comment by cagnulein** [comment]
great! consider that for the zwift api new feature you need the version from the play store directly. I will have to push it in the next days

**Comment by rjkibler** [comment]
Hi, Roberto! 

Do you have an idea when you will be pushing the app update to the play store? I am just hoping to play around with it this weekend, but no worries if not!

Hope you are having a great start to your weekend! 

Best, 
Ryan

**Comment by cagnulein** [comment]
google is requiring a lot of days lately. on the store are you still seeing version 2.16.38?

**Comment by rjkibler** [comment]
It's version 2.16.30 on the play store.

Best,
Ryan

**Comment by cagnulein** [comment]
ok so send me your Gmail account associated to the play Store account on
this email roberto.viola83 at gmail.com and I will add you to the closed
beta

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 27 gen 2024 alle 13:22 Ryan Kibler ***@***.***>
ha scritto:

**Comment by rjkibler** [comment]
My play store account email is ***@***.***

Thanks!

**Comment by cagnulein** [comment]
@rjkibler are we ok with this?
