### ISSUE TITLE
[BUG] Nautilus T628 Issue

### ISSUE THREAD

**Issue by DavidWiseman** [cagnulein/qdomyos-zwift#2043]
**Describe the bug**
The treadmill is detected but it doesn't display any information and the start button is flashing red.

![image](https://github.com/cagnulein/qdomyos-zwift/assets/33157668/c611f8d3-0b63-4fdc-9f05-2cc4f334108f)

There is a [similar bug](https://github.com/cagnulein/qdomyos-zwift/issues/1318) for the T618 model so I think this might require a similar fix.

[debug-Wed_Jan_24_16_17_00_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14041341/debug-Wed_Jan_24_16_17_00_2024.log)

Thanks.  I'm using a Runn treadmill sensor but this app would be a big improvement.  😊

**Comment by cagnulein** [comment]
@DavidWiseman got the issue and fixed

https://github.com/cagnulein/qdomyos-zwift/actions/runs/7643563701

Google is very slow in these days, reviewing the app on the store, even the beta ones. For this reason, in order to check right now if the patch that I did is right, you can use the android build in the link (check at the bottom of the page in about 1 hour). In order to test it you need first to remove the current QZ version on your phone, install the one that you downloaded.
This version is a 15 minutes trial (you can restart it as many times as you want) and I can unlock it if you want, send me an email to roberto.viola83@gmail.com mentioning this ticket and that you are on android.
Let me know if you have any questions

**Comment by DavidWiseman** [comment]
Wow.  That's a fast response. 😊

I'll report back when I've been able to test it.

**Comment by DavidWiseman** [comment]
Hi, I've done a quick test - it's fixed. 🎉

It doesn't pick up the incline but that might be a limitation of the treadmill.

**Comment by cagnulein** [comment]
great! about the inclination i could check if you want. just add a debug
log.

tomorrow i will push the version in the play store

send me an email to roberto.viola83 at gmail.com in order to add you to
closed beta of qz

Let me know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 24 gen 2024 alle 22:05 David Wiseman ***@***.***>
ha scritto:

**Comment by DavidWiseman** [comment]
Thanks.  I logged a new issue for the incline with the debug log [here](https://github.com/cagnulein/qdomyos-zwift/issues/2046).

Thanks for adding my email. 😊
