### ISSUE TITLE
Support for Proform 705 CST

### ISSUE THREAD

**Issue by RuiRodrigues1977** [cagnulein/qdomyos-zwift#2090]
Hi,

Could you please add  Proform 705 CST treadmill (model PETL99717.1) to QZ app.

I connected to my treadmill with the IFIT application, started a workout and increased the inclination and speed several times up to 20km/h and 12 degrees. Attached bt file
[btsnoop_hci.log](https://github.com/cagnulein/qdomyos-zwift/files/14131204/btsnoop_hci.log)

Thank you
Rui Rodrigues

**Comment by cagnulein** [comment]
Thanks I will check this asap

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 1 feb 2024 alle 22:29 RuiRodrigues1977 <
***@***.***> ha scritto:

**Comment by cagnulein** [comment]
[formatted_code.txt](https://github.com/cagnulein/qdomyos-zwift/files/14140414/formatted_code.txt)
here the full extracted code, i'm adding it

**Comment by cagnulein** [comment]
done @RuiRodrigues1977 
https://github.com/cagnulein/qdomyos-zwift/actions/runs/7756549527

I added a new device in the combobox of the proform treadmills for this model

Google is very slow in these days, reviewing the app on the store, even the beta ones. For this reason, in order to check right now if the patch that I did is right, you can use the android build in the link (check at the bottom of the page in about 1 hour). In order to test it you need first to remove the current QZ version on your phone, install the one that you downloaded.
This version is a 15 minutes trial (you can restart it as many times as you want) and I can unlock it if you want, send me an email to roberto.viola83@gmail.com mentioning this ticket and that you are on android.
Let me know if you have any questions

**Comment by RuiRodrigues1977** [comment]
Hi Roberto,

I tried this Android version and everything seems to work wonderfully, speed and inclination controllable from the QZ app. Later I will try with Zwift.

You are the best.

Thank you

**Comment by cagnulein** [comment]
Glad to hear it!
this is not working with Zwift because it's just a trial version. I will
upload as soon as possible on the store. Send me an email to
Roberto.viola83 at Gmail.com indicating this ticket and I will add you to
the closet beta

Il giorno ven 2 feb 2024 alle 18:13 RuiRodrigues1977 <
***@***.***> ha scritto:
