### ISSUE TITLE
NordicTrack Elite 4000 [BUG]

### ISSUE THREAD

**Issue by PedroMiguSantos** [cagnulein/qdomyos-zwift#2113]
QZ does not obtain data from NordicTrack Elite 4000, and neither can command the treadmill. The treadmill is wifi based,
QZ is showing the tiles, but they remain at zero when the treadmill is moving and with incline.
The treadmill's IP was inserted on the option of the Nordictrack 2950, and Proform (one at a time).
Can ping the treadmill from the tablet.
Debug log attached.

[debug-Sat_Feb_10_11_48_50_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14229210/debug-Sat_Feb_10_11_48_50_2024.log)

QZ is installed on a tablet Lenovo P11 Plus with android 11.
Don't know the android version of the treadmill but it can be android 4, 5 or 6.

Thank you!

**Comment by cagnulein** [comment]
@PedroMiguSantos in this log you still have the ip in the 2950. remove it and press ok and then set it in the proform ip setting and press ok and restart qz

let me know

**Comment by PedroMiguSantos** [comment]
Feeling dumb now. Guess when I tried the IP on proform option, I inserted a
wrong one. It is now working with the proform option. You can add the
Nordictrack elite 4000 to the list of compatible treadmills.

Thank you for the support, and sorry to waste your time.

Cheers Pedro

A sábado, 10/02/2024, 12:35, Roberto Viola ***@***.***>
escreveu:

**Comment by cagnulein** [comment]
amazing news!

**Comment by PedroMiguSantos** [comment]
Adding debug log to study the possibility of QZ sending negative inclinations to the treadmill.
It would be great to run on Zwift with autoincline working with negative inclinations.

[debug-Sat_Feb_10_14_38_06_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14229608/debug-Sat_Feb_10_14_38_06_2024.log)

**Comment by cagnulein** [comment]
thanks i will do next week!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 10 feb 2024 alle 15:56 PedroMiguSantos <
***@***.***> ha scritto:

**Comment by cagnulein** [comment]
done! it will be in the 2.16.42

**Comment by PedroMiguSantos** [comment]
Just one more thing, Roberto. Didn't bothered with this earlier because it was Saturday.
I noticed an issue with speed synchronization between QZ and the treadmill, for example: If the speed is like 12km/h and then I suddenly change it to 8km/h, the QZ speed will drop to 4.6km/h and then to zero in one second while the speed on the treadmill remains at 8. I have to press on the 12km/h button on the treadmill again and then on 8km/h again for QZ to stay at that speed without dropping to zero again.
I'm attaching the bug log for your review.

Again thank you for your amazing support.

[debug-Sat_Feb_10_19_13_31_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14238011/debug-Sat_Feb_10_19_13_31_2024.log)

**Comment by cagnulein** [comment]
it seems a firmware bug of the treadmill, check this

here you are pressing the 6 km/h button
sábado fev. 10 19:14:06 2024 1707592446858 Debug: ../src/bluetooth.cpp void bluetooth::debug(const QString &) " << { \"values\":{ \"key\":{\"code\":\"1105\", \"held\":\"261\", \"name\":\"QUICK KPH 6\"}} }"
sábado fev. 10 19:14:06 2024 1707592446859 Debug: ../src/bluetooth.cpp void bluetooth::debug(const QString &) " << { \"values\":{ \"key\":{\"code\":\"1105\", \"held\":\"-1\", \"name\":\"QUICK KPH 6\"}} }"

here the treadmill i sending speed 4.0 km/h
sábado fev. 10 19:14:09 2024 1707592449655 Debug: ../src/bluetooth.cpp void bluetooth::debug(const QString &) " << { \"values\":{ \"Current MPH\":\"2.5\", \"Current KPH\":\"4.0\", \"Miles\":\"0.034\", \"Kilometers\":\"0.054\" } }"

here you are pressing 12km/h button
sábado fev. 10 19:14:10 2024 1707592450271 Debug: ../src/bluetooth.cpp void bluetooth::debug(const QString &) " << { \"values\":{ \"key\":{\"code\":\"1111\", \"held\":\"7\", \"name\":\"QUICK KPH 12\"}} }"
sábado fev. 10 19:14:10 2024 1707592450273 Debug: ../src/bluetooth.cpp void bluetooth::debug(const QString &) " << { \"values\":{ \"MPH\":\"7.4\", \"KPH\":\"12.0\", \"key\":{\"code\":\"1111\", \"held\":\"48\", \"name\":\"QUICK KPH 12\"}} }"
sábado fev. 10 19:14:10 2024 1707592450278 Debug: ../src/bluetooth.cpp void bluetooth::debug(const QString &) " << { \"values\":{ \"Total Time\":\"57:59:21\", \"Total Miles\":\"226\", \"key\":{\"code\":\"1111\", \"held\":\"103\", \"name\":\"QUICK KPH 12\"}} }"
sábado fev. 10 19:14:10 2024 1707592450484 Debug: ../src/bluetooth.cpp void bluetooth::debug(const QString &) " << { \"values\":{ \"key\":{\"code\":\"1111\", \"held\":\"-1\", \"name\":\"QUICK KPH 12\"}} }"

the treadmill is sending 4.6 km/h
sábado fev. 10 19:14:11 2024 1707592451532 Debug: ../src/bluetooth.cpp void bluetooth::debug(const QString &) " << { \"values\":{ \"Current MPH\":\"2.9\", \"Current KPH\":\"4.6\", \"Miles\":\"0.038\", \"Kilometers\":\"0.061\" } }"

the treadmill is sending 0 km/h
sábado fev. 10 19:14:13 2024 1707592453473 Debug: ../src/bluetooth.cpp void bluetooth::debug(const QString &) " << { \"values\":{ \"Current MPH\":\"0.0\", \"Current KPH\":\"0.0\", \"Miles\":\"0.042\", \"Kilometers\":\"0.067\" } }"

here you are pressing the 6 km/h button
sábado fev. 10 19:14:18 2024 1707592458952 Debug: ../src/bluetooth.cpp void bluetooth::debug(const QString &) " << { \"values\":{ \"key\":{\"code\":\"1105\", \"held\":\"6\", \"name\":\"QUICK KPH 6\"}} }"
sábado fev. 10 19:14:18 2024 1707592458953 Debug: ../src/bluetooth.cpp void bluetooth::debug(const QString &) " << { \"values\":{ \"MPH\":\"3.7\", \"KPH\":\"6.0\", \"key\":{\"code\":\"1105\", \"held\":\"27\", \"name\":\"QUICK KPH 6\"}} }"


maybe the issue is that you are pressing these keys too fast? does it happen also if you wait 10 seconds for example between each changes?

**Comment by PedroMiguSantos** [comment]
It might be the firmware, but it also happens when I wait more than 10 seconds to change the speed. I also noticed that it usually happens when I change to speeds inferior to  6.5km/h.
I made a video showcasing the problem and the correspond bug log.
This is not an major issue, it bothers mostly my wife because she's the one that rests at those speeds when doing intervals :D :D

[debug-Mon_Feb_12_16_59_53_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14244908/debug-Mon_Feb_12_16_59_53_2024.log)

[video](https://photos.app.goo.gl/MGZajFbTAmXEjiTe9)

**Comment by cagnulein** [comment]
Does it also without qz?

**Comment by PedroMiguSantos** [comment]
No. The treadmill functions as expected, only the speed displayed on QZ's
speed tile goes to zero (consequently on zwift) while the treadmill
continues on the ordered speed.
The treadmill functions normally without QZ.


A segunda, 12/02/2024, 17:50, Roberto Viola ***@***.***>
escreveu:

**Comment by cagnulein** [comment]
ok i will check the log again tomorrow

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 12 feb 2024 alle 18:56 PedroMiguSantos <
***@***.***> ha scritto:

**Comment by cagnulein** [comment]
log checked and yes it's a firmware bug of the treadmill about the metrics transmission.
If you are instead changing the speed from qz, there is the same issue as well?
If not i suggest to use the preset speed and incline buttons from qz to avoid this

**Comment by PedroMiguSantos** [comment]
I did not try qz controls to chance the speed, I'll do it tomorrow. But as
I said before it's major issue. :)

Thank you Roberto

A terça, 13/02/2024, 12:36, Roberto Viola ***@***.***>
escreveu:

**Comment by PedroMiguSantos** [comment]
*not
