### ISSUE TITLE
[BUG]Domyos Challenge Bike (TC-0421) crashes app

### ISSUE THREAD

**Issue by Banetta88** [cagnulein/qdomyos-zwift#2120]
**Describe the bug**
The qz domyos app on Android smartphone & Tablet crashes when it connects to the bike. It recognizes the bike, it connects but shortly after that the qz app crashes.

**To Reproduce**
1 turn on the bike
2 start qz domyos app
3 qz domyos app connects with bike for a second
4 app crashes to homescreen 

**Expected behavior**
App connects with the bike and stays connected

**Screenshots**
![426833004_3408233839481199_7125641810487778250_n (1)](https://github.com/cagnulein/qdomyos-zwift/assets/159730802/90193093-7619-4316-b3d2-22c428925565)
![1707687954043](https://github.com/cagnulein/qdomyos-zwift/assets/159730802/c69194ed-594b-4ebf-9587-14b7c44ebd8f)
![1707687954038](https://github.com/cagnulein/qdomyos-zwift/assets/159730802/f519b9c6-7560-4535-9dfd-c36b4668c044)

**Smartphone (please complete the following information):**
 - Xiaomi 11T Pro
 - MIUI 14
 - 14.0.14

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
thanks i will add it tomorrow!

**Comment by cagnulein** [comment]
hi @Banetta88 
done! https://github.com/cagnulein/qdomyos-zwift/actions/runs/7866100027

Google is very slow in these days, reviewing the app on the store, even the beta ones. For this reason, in order to check right now if the patch that I did is right, you can use the android build in the link (check at the bottom of the page in about 1 hour). In order to test it you need first to remove the current QZ version on your phone, install the one that you downloaded.
This version is a 15 minutes trial (you can restart it as many times as you want) and I can unlock it if you want, send me an email to roberto.viola83@gmail.com mentioning this ticket and that you are on android.
Let me know if you have any questions

**Comment by cagnulein** [comment]
@Banetta88 are we ok with this?

**Comment by Banetta88** [comment]
Hey, connection is stable.
The only thing I have to check is the resistance ratio.
The Challenge bike has 32 resistance levels but it seems like the scaling is a bit off. 100% target resistance is resistance level 25 on bike. 
Maybe I need to play around with the options in the app

**Comment by cagnulein** [comment]
are you using qz with zwift? or standalone? in case share here a debug log and I will check it

**Comment by Banetta88** [comment]
Connected with Zwift as standalone.
The scaling thing was with peloton. I'll test it in the next few days and let you know

**Comment by Banetta88** [comment]
Attached the debug file:
[debug-Fri_Feb_16_13_22_22_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14311110/debug-Fri_Feb_16_13_22_22_2024.log)

If I use the peloton app and for example the resistance is set to 25 (1-100) by the app, the challenge bike is set to level 9 (1-32). At the app´s default of 45, the bike sets to 11.
Is it possible to adjust the scaling of the resistance?

**Comment by cagnulein** [comment]
@Banetta88 any news?
