### ISSUE TITLE
Pasyou S70 bike can connect but no data given.

### ISSUE THREAD

**Issue by Result6393** [cagnulein/qdomyos-zwift#2168]
**Describe the bug**
I have an exercise bike that I'm having trouble connecting to cycling apps. It is a Pasyou S70, listed as an iconsole bike and *should* have FTMS. It connects to the qdomyus app but no cycling data is showing up in the app. Futhermore, it can only connect to Zwift or other cycling apps directly by using speed/cadence data. However, it does connect to Kinomap directly (without qdomyus).

I have Toorx/iconsole enabled in settings.
I have the bike manually selected in the advanced settings.

**Smartphone (please complete the following information):**
 - Device: Pixel 7 Pro and Samsung Galaxy S10. Both have same issue.
 - Android 14 and Android 12. Same issue for both.
 - Version: 2.16.46 and 2.14.0

Screenshots and debug log attached.
As an iconsole bike, is it compatible with your app? Thank you very much for your time and help!

![Screenshot_20240229-224327](https://github.com/cagnulein/qdomyos-zwift/assets/105765953/30902a00-a061-40c4-968a-5f61846b3e2f)
![Screenshot_20240229-224338](https://github.com/cagnulein/qdomyos-zwift/assets/105765953/8b43029c-5f01-4560-9df9-8e555044d863)
![Screenshot_20240229-224409](https://github.com/cagnulein/qdomyos-zwift/assets/105765953/5d7e4b95-2f96-4301-85b7-26d1d6b9206f)
![Screenshot_20240229-224509](https://github.com/cagnulein/qdomyos-zwift/assets/105765953/99cfde72-d53d-46c2-82aa-b1cde1318d99)
![Screenshot_20240229-232319_nRF Connect](https://github.com/cagnulein/qdomyos-zwift/assets/105765953/4be1b33a-4eba-42cc-9e0e-6c8f3dc94d74)
here.
[debug-Thu_Feb_29_22_44_03_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14447871/debug-Thu_Feb_29_22_44_03_2024.log)

**Comment by cagnulein** [comment]
Hi @Result6393 added!
https://github.com/cagnulein/qdomyos-zwift/actions/runs/8096301174
Google is very slow in these days, reviewing the app on the store, even the beta ones. For this reason, in order to check right now if the patch that I did is right, you can use the android build in the link (check at the bottom of the page in about 1 hour). In order to test it you need first to remove the current QZ version on your phone, install the one that you downloaded.
This version is a 15 minutes trial (you can restart it as many times as you want) and I can unlock it if you want, send me an email to roberto.viola83@gmail.com mentioning this ticket and that you are on android.
Let me know if you have any questions

**Comment by cagnulein** [comment]
@Result6393 are we ok with this?

**Comment by Result6393** [comment]
Thanks for following up on this. The updated version of the app does appear to be working. However, I suspect that this particular bike does not actually transmit power information, and only transmits speed/cadence. It's a bit strange because the built in screen does show power information.
Thank you for your time anyway!

**Comment by cagnulein** [comment]
If you want I can check it, upload here a debug log https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
