### ISSUE TITLE
[BUG] QZ App will connect to but not report data for Nautilus E618 Elliptical

### ISSUE THREAD

**Issue by RonnieTheBear** [cagnulein/qdomyos-zwift#2188]
**Describe the bug**

**To Reproduce**
1. Elliptical is powered on, excercise program has been started, actively moving pedals
2. Open QZ App
3. QZ App shows "Nautilus E618 Found", bluetooth connection light activates on elliptical
4. QZ will not report any actual data for workout - no RPM shown, no speed, inclination, etc.

**Expected behavior**
QZ should show actual data for workout once connected and using the equipment - RPM , speed, inclination, etc.

**Screenshots**
![unnamed](https://github.com/cagnulein/qdomyos-zwift/assets/114628922/df28a949-f6c0-4143-a281-66e1629eff62)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S22
 - OS: Android 14
 - QZ App Version 2.16.46

Debug log attached. Suspect the line that says:
Critical: qrc:/ChartFooterInnerJS.qml onLoadingChanged net::ERR_CONNECTION_REFUSED
after the app attempts a BTLE connection to the elliptical may be culprit.

[debug-Tue_Mar_5_12_42_35_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14499332/debug-Tue_Mar_5_12_42_35_2024.log)

**Comment by cagnulein** [comment]
@RonnieTheBear already got the issue, are you able to download the free app nrfconnect and send me a screenshot from it of your elliptical

I guess the reason any easy fix for this 

Let me know

**Comment by cagnulein** [comment]
@RonnieTheBear done!
https://github.com/cagnulein/qdomyos-zwift/actions/runs/8161014471
Google is very slow in these days, reviewing the app on the store, even the beta ones. For this reason, in order to check right now if the patch that I did is right, you can use the android build in the link (check at the bottom of the page in about 1 hour). In order to test it you need first to remove the current QZ version on your phone, install the one that you downloaded.
This version is a 15 minutes trial (you can restart it as many times as you want) and I can unlock it if you want, send me an email to roberto.viola83@gmail.com mentioning this ticket and that you are on android.
Let me know if you have any questions

**Comment by RonnieTheBear** [comment]
That did the trick, thank you!! I will email you about an unlock code.

![Screenshot_20240305_171310](https://github.com/cagnulein/qdomyos-zwift/assets/114628922/e4214c1f-d1a6-4e6f-8376-d6335edb1456)

**Comment by cagnulein** [comment]
That's great!

**Comment by JanSob** [comment]
Hi @cagnulein !
I just bought the app on iOS and I am having the exact same issue with my Nautilus T628 (the app says it found it, but no actual data is shown). Apparently this issue seems to have been fixed on Android...has it been also fixed in the iOS-Version of the App?

**Comment by cagnulein** [comment]
Hi @JanSob i guess it's a different issue because the patch is already in the production version. Could you please send me a debug log? https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F

**Comment by JanSob** [comment]
@cagnulein wow, that was a fast response :-) 
I pedaled for 3 minutes and attached the log, if you need any other logs (with some specific settings enabled etc) just let me know.

[debug-Sat_Mar_29_15_13_46_2025.log](https://github.com/user-attachments/files/19521530/debug-Sat_Mar_29_15_13_46_2025.log)

**Comment by cagnulein** [comment]
I guess I found the root cause. Could you please share a nrfconnect
screenshot about this elliptical showing all the charactistics.

Nrfconnect is a free app on the store

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 29 mar 2025 alle 15:21 JanSob ***@***.***> ha
scritto:

**Comment by JanSob** [comment]
@cagnulein I made 3 screenshot, the third one is after i tapped on "Connect" in the Nrfconnect-App.

![Image](https://github.com/user-attachments/assets/c5560dda-8df3-47d7-9087-ae4728010067)

![Image](https://github.com/user-attachments/assets/e73f0907-3cb7-4350-b502-7c43133d7f32)

![Image](https://github.com/user-attachments/assets/deb5a939-92b9-434e-8794-22bea2942c3b)

**Comment by cagnulein** [comment]
Please click also on the icon with 3 lines and 3 dots in the top part of the screen and show me the characteristics there

Thanks

**Comment by JanSob** [comment]
![Image](https://github.com/user-attachments/assets/67ff04f3-1162-4dfd-a201-b696ce964b62)

**Comment by JanSob** [comment]
@cagnulein

[Nautilus E628.txt](https://github.com/user-attachments/files/19521643/Nautilus.E628.txt)

**Comment by cagnulein** [comment]
Can you try to disconnect and connect again? We should see a list there

**Comment by cagnulein** [comment]
Perfect! I will add it ASAP!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 29 mar 2025 alle 15:48 JanSob ***@***.***> ha
scritto:

**Comment by JanSob** [comment]
@cagnulein oh yes, now there are many more infos:

![Image](https://github.com/user-attachments/assets/77b9d839-a1e3-427b-b39e-39e7349297a6)

![Image](https://github.com/user-attachments/assets/db71e785-c451-49d9-b5d5-6800c4e5934b)

![Image](https://github.com/user-attachments/assets/8095ca94-98be-48c9-a931-39d11c4ac411)

![Image](https://github.com/user-attachments/assets/deb8d6b4-4c5b-40eb-ae2a-2b94b8d02a3a)

![Image](https://github.com/user-attachments/assets/c06a5000-9684-4f71-971a-5339e865195e)

![Image](https://github.com/user-attachments/assets/c0416759-dc54-4baa-8909-b55caad2440d)

**Comment by JanSob** [comment]
> Perfect! I will add it ASAP!
> 
> Roberto Viola
> Software engineer and open source enthusiast
> http://robertoviola.cloud
> 
> 
> 
> Il giorno sab 29 mar 2025 alle 15:48 JanSob ***@***.***> ha
> scritto:
> […](#)

Oh wow, nice :-) 
If you need any additional logs etc just let me know :-)

**Comment by cagnulein** [comment]
@JanSob done! send me an email to roberto.viola83 at gmail.com indicating this ticket and if you are on android or iOS. Thanks

**Comment by JanSob** [comment]
@cagnulein i just tested the app, and now the resistance levels are perfectly reflected in the app, which is great! But it is only resistance that is shown, is that normal? Things like Speed or Watt are not reflected. 

I attached the debug-log, app-screenshot, and also 3 screenshots (one can switch between screens) of what the elliptical is showing on both of its displays (Speed, Level, RPM, Watts etc) .

[debug-Sun_Mar_30_12_43_33_2025.log](https://github.com/user-attachments/files/19525259/debug-Sun_Mar_30_12_43_33_2025.log)

![Image](https://github.com/user-attachments/assets/3211d358-de75-49b7-a3c3-2a934fc5937e)

![Image](https://github.com/user-attachments/assets/726af8e5-4c91-4ed7-950c-d04d0d94a094)

![Image](https://github.com/user-attachments/assets/3099638d-c379-41b0-8d85-a5f36a3df96d)

![Image](https://github.com/user-attachments/assets/59454b6b-9d1a-4cd3-b635-37572cb12e88)

**Comment by cagnulein** [comment]
Got it, I need to do another little patch. I will try to do it ASAP

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 30 mar 2025 alle 12:57 JanSob ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
New version sent! Let me know!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 30 mar 2025 alle ore 13:26 cagnulein ***@***.***> ha
scritto:

**Comment by JanSob** [comment]
@cagnulein 

Wow, it shows many values, this is really great :-) 
What is absolutely perfect is _RPM_ and the _Resistance_, they match the elliptical perfectly.

What has wrong values // suddenly maxes out
_Speed_: 
- Value shown in the app is always 2-3 km/h less than on the elliptical
- Also value suddenly maxes out to a very high number (see screenshot) when the elliptical itself gets over 6 km/h

_Watt_:
- Value is correct, but when over 75 watt, the app suddenly maxes out (see screenshot).

Maybe some buffer overflow?

It’s awesome that you were able to get it to work this far!
I won’t be at home for the next days (will be back on Thursday evening), I will then run a longer session and post the debug.log in here.

The attached debug log is just from a short test-session right now (I had to zip it, because the uncompressed log-file was 27mb for some strange reason and would fail the github upload?).

Thank you for your great work!

![Image](https://github.com/user-attachments/assets/e98e7599-55c7-45a8-8319-37904f99fa41)

[debug-Sun_Mar_30_16_43_57_2025.log.zip](https://github.com/user-attachments/files/19526229/debug-Sun_Mar_30_16_43_57_2025.log.zip)

**Comment by cagnulein** [comment]
Thanks I will check in the next days!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 30 mar 2025 alle 17:12 JanSob ***@***.***> ha
scritto:

**Comment by JanSob** [comment]
@cagnulein Hi! The values do not max out anymore, which is great! The speed-value is a bit lower than on the elliptical, i have send you an email with a video and the log.

**Comment by cagnulein** [comment]
I guess I got the issue. The elliptical sends it in Miles/h instead of
KM/h. If so the speed in qz should be actual speed * 1.6. Does it sound
right to you?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 1 apr 2025 alle ore 23:20 JanSob ***@***.***>
ha scritto:

**Comment by JanSob** [comment]
This was exactly the issue, it was in miles, it's correct now!
