### ISSUE TITLE
No metrics while connected to ECHELON EX-15[BUG]

### ISSUE THREAD

**Issue by mtuyizere** [cagnulein/qdomyos-zwift#2248]
QZ is connecting to ECHELON - EX 15 via bluetooth but metrics like cadence are reading zero
This used to work ok but also was not able to connect to zwift app. 
While using Echelon app all metrics are working properly.
here attached the debug log.

[QZ Debug.zip](https://github.com/cagnulein/qdomyos-zwift/files/14729417/QZ.Debug.zip)

**Comment by cagnulein** [comment]
The problem is that you set the bike also as cadence and power sensor
setting. Remove from them and press OK on both and restart qz
Let me know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 23 mar 2024 alle 00:59 mtuyizere ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
@mtuyizere are we ok with this?
