### ISSUE TITLE
[BUG] Elevation gain increas also with inclination set to zero or to a negative value

### ISSUE THREAD

**Issue by Fabrix78** [cagnulein/qdomyos-zwift#2259]
**Describe the bug**
As described in the title

**To Reproduce**
1. Start the treadmill
2. Maintain the inclination to 0%, the speed value isn't relevant
3. The elevation gain increas about 0,5 - 0,8 m/min
4. Set the inclination to a negative value (Toorx altitude can go just to - 2%)
5. The elevation gain increas more

**Expected behavior**
Whit inclination set to 0% or to a negative value the elevation gain must be 0. 

**Screenshots**

**Desktop (please complete the following information):**
 

**Smartphone (please complete the following information):**
 - Device: [Xiaomi Mi Note 10 ]
 - OS: [Android]
 - Version [11]

**Append a debug log**

 
[debug-Wed_Mar_27_20_13_40_2024 (2).log](https://github.com/cagnulein/qdomyos-zwift/files/14781549/debug-Wed_Mar_27_20_13_40_2024.2.log)

  
  
**Additional context**

**Comment by cagnulein** [comment]
Thanks I will check it ASAP

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 27 mar 2024 alle 23:07 Fabrix78 ***@***.***> ha
scritto:

**Comment by Fabrix78** [comment]
I followed your instructions and took the test again:
When i start the treadmill with zero inclination the elevation gain stay to zero, but if I increase the inclination and then put it back to zero the elevation gain increase again about 0,5 m/min. Also with a negative inclination value the inclination gain increase. 
It maybe that I need to change some settings from the settings menu? 

Here you can find the debug file. 
Thanks for your help. 

[debug-Fri_Mar_29_15_33_21_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14811017/debug-Fri_Mar_29_15_33_21_2024.log)

**Comment by cagnulein** [comment]
ok, i will check this after easter days. Happy easter
Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 30 mar 2024 alle ore 08:36 Fabrix78 ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
got the issue, and fixed. it seems a bug of the treadmill. When you are back to 0 the treadmill sends me a -1 instead. The fix will be in the 2.16.51

If you want to check immediately https://github.com/cagnulein/qdomyos-zwift/actions/runs/8495530098

Google is very slow in these days, reviewing the app on the store, even the beta ones. For this reason, in order to check right now if the patch that I did is right, you can use the android build in the link (check at the bottom of the page in about 1 hour). In order to test it you need first to remove the current QZ version on your phone, install the one that you downloaded.
This version is a 15 minutes trial (you can restart it as many times as you want) and I can unlock it if you want, send me an email to roberto.viola83@gmail.com mentioning this ticket and that you are on android.
Let me know if you have any questions

**Comment by cagnulein** [comment]
any news?

**Comment by Fabrix78** [comment]
Hi,
sorry, but I haven't been able to use the treadmill until today. I tested the new app release and the problem of the increase of the elevation gain with negative inclination is fixed. I can notice two minor problems...with zero inclination the elevation gain still increase about 0,5 m/min and with negative inclination the total elevation gain decrease. So if I walk up for 1000 meters and then walk down for 200 meters the total of elevation gain shown by the app is 800 meters instead of the correct value of 1000.

Here the degud file:
[debug-Sat_Apr_20_09_47_03_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/15049545/debug-Sat_Apr_20_09_47_03_2024.log)

Thank for your work!

**Comment by cagnulein** [comment]
@Fabrix78 any news?
