### ISSUE TITLE
[BUG] Hearth data not showing on QZ App

### ISSUE THREAD

**Issue by nixrand** [cagnulein/qdomyos-zwift#2349]
Problem: My hearth data is not  showing on QZ App 

Using on same phone:  QZ App + Garmin connect ( i see hearth data)
Watch: Garmin 945  with QZ Companion (i see hearth data)

start qz companion + start qz app , but no heart data is displayed.

Attached debug log file.
[debug-Wed_May_22_16_01_45_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/15404431/debug-Wed_May_22_16_01_45_2024.log)

**Comment by cagnulein** [comment]
You need to enable the garmin companion setting in qz and restart qz
Let me know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 22 mag 2024 alle 16:11 nixrand ***@***.***> ha
scritto:

**Comment by nixrand** [comment]
I enabled garmin companion setting + restart app  but the problem persists...

**Comment by cagnulein** [comment]
Send me a debug log in this scenario. Is the phone of qz paired with the
watch with also garmin connect installed?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 22 mag 2024 alle 17:27 nixrand ***@***.***> ha
scritto:

**Comment by nixrand** [comment]
phone with garmin connect installed is pared with  the phone as you could see in this screenshot.

Attached debug file

[debug-Wed_May_22_17_35_56_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/15405701/debug-Wed_May_22_17_35_56_2024.log)
![qz-companion_and_garmin_connect](https://github.com/cagnulein/qdomyos-zwift/assets/97276246/9e9d7419-2423-45fd-9f96-3071a9d35f5c)

**Comment by cagnulein** [comment]
Can you try to join the beta here
https://play.google.com/apps/testing/org.cagnulen.qdomyoszwift

And update the app on the Google play and try again?

Let me know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 22 mag 2024 alle 17:43 nixrand ***@***.***> ha
scritto:

**Comment by nixrand** [comment]
[debug-Thu_May_23_05_42_45_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/15411269/debug-Thu_May_23_05_42_45_2024.log)

installed beta version and same problem, not showing hearth data on qz app ( qz companion and garmin connect data are openeed and displaying data ok). All of them (qz app+ garmin) on same phone

**Comment by cagnulein** [comment]
Fixed https://github.com/cagnulein/qdomyos-zwift/actions/runs/9202679539 


Google is very slow in these days, reviewing the app on the store, even the beta ones. For this reason, in order to check right now if the patch that I did is right, you can use the android build in the link (check at the bottom of the page in about 1 hour). In order to test it you need first to remove the current QZ version on your phone, install the one that you downloaded.
This version is a 15 minutes trial (you can restart it as many times as you want) and I can unlock it if you want, send me an email to roberto.viola83@gmail.com mentioning this ticket and that you are on android.
Let me know if you have any questions

**Comment by nixrand** [comment]
It works with this fix.  Thanks a lot Roberto
