### ISSUE TITLE
[BUG] Cadence gain not working on proform tour de france cbc bike

### ISSUE THREAD

**Issue by Hohenheimsenberg** [cagnulein/qdomyos-zwift#2350]
I have a Tour de france cbc bike, it has one magnet missing that reports cadence. So my cadence in the screen of the bike is always half of what I'm really pedaling.
I wanted to use the QZ cadence gain but setting it to 2 or any other number doesn't seem to do anything. I also have tried to change the watt gain, speed gain and those do not work as well.

[debug-Wed_May_22_16_50_25_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/15409568/debug-Wed_May_22_16_50_25_2024.log)
[settings_default_20240323135736.zip](https://github.com/cagnulein/qdomyos-zwift/files/15409575/settings_default_20240323135736.zip)

**Comment by cagnulein** [comment]
Fixed https://github.com/cagnulein/qdomyos-zwift/actions/runs/9202565266


Google is very slow in these days, reviewing the app on the store, even the beta ones. For this reason, in order to check right now if the patch that I did is right, you can use the android build in the link (check at the bottom of the page in about 1 hour). In order to test it you need first to remove the current QZ version on your phone, install the one that you downloaded.
This version is a 15 minutes trial (you can restart it as many times as you want) and I can unlock it if you want, send me an email to roberto.viola83@gmail.com mentioning this ticket and that you are on android.
Let me know if you have any questions

**Comment by cagnulein** [comment]
@Hohenheimsenberg  any news?

**Comment by Hohenheimsenberg** [comment]
Yes, bug is fixed with this change.
