### ISSUE TITLE
[BUG]Zwift Auto Incline not working on Nordictrack X22i

### ISSUE THREAD

**Issue by ufu-** [cagnulein/qdomyos-zwift#2353]
[debug-Sat_May_25_12_41_49_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/15441779/debug-Sat_May_25_12_41_49_2024.log)
**Describe the bug**

I cannot get the Zwift auto incline to work on PC & NordicTrack X22i (AU)

**To Reproduce**
QZ successfully connects to the treadmill
QZ can control speed and incline with the +/- buttons 
Zwift sees the treadmill and identifies speed changes if I manually do so from the console 
I am still able to manually change incline from the console
Unfortunately nothing happens automatically when the incline changes in Zwift

**Desktop (please complete the following information):**
 - OS: (Windows 11 23H2 22531..3593 ) 
 - QZ 2.16.55 (msvc)

**Append a debug log**
Please see debug Attached
  
  
**Additional context**
The debug includes 3 short runs, the first one did not have any incline change finally the third one had some towards the end.
I did briefly manually change the incline form 0 to 0.5 and back in the first run.

**Comment by ufu-** [comment]
[debug-Sat_May_25_12_41_49_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/15441783/debug-Sat_May_25_12_41_49_2024.log)

**Comment by ufu-** [comment]
[Uploading debug-Sat_May_25_13_29_03_2024.log…]()

**Comment by ufu-** [comment]
[debug-Sat_May_25_13_29_03_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/15441819/debug-Sat_May_25_13_29_03_2024.log)

**Comment by ufu-** [comment]
[debug-Mon_May_27_16_51_56_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/15453845/debug-Mon_May_27_16_51_56_2024.log)
[debug-Mon_May_27_16_37_00_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/15453869/debug-Mon_May_27_16_37_00_2024.log)

**Comment by cagnulein** [comment]
I was checking the differences between the PC and iOS log and yeah, you are right, the major one is 

`Mon May 27 16:37:15 2024 1716799035833 Debug: ../src/zwift-api/PlayerStateWrapper.h QByteArray ZwiftRequest::protobuf(const QString &) Error:  "Error transferring https://us-or-rly101.zwift.com/relay/worlds/1/players/5739728 - server replied: Not Found"`

Since the code is actually the same between the PC one and the iOS one, the only thing that I could think of is the fact that this url is not avaiable on the pc side. Maybe some firewall issue?

**Comment by cagnulein** [comment]
@ufu- any news?
