### ISSUE TITLE
Sole ST90 BT HCI Snoop log[REQ]

### ISSUE THREAD

**Issue by bzwolf** [cagnulein/qdomyos-zwift#2355]
I started the activity from the Sole App, went up in incline, down, then up fully to 15. Down most of the way, back up a couple of times, then back down to 0 and stopped the activity. If that isn't specific enough please let me know and I'll repeat with exact steps. 
[btsnoop_hci.log](https://github.com/cagnulein/qdomyos-zwift/files/15445718/btsnoop_hci.log)

**Comment by cagnulein** [comment]
Thanks! I will check it in the next few days

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 26 mag 2024 alle 03:34 bzwolf ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
I will handle your case tomorrow, it's very easy actually

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 26 mag 2024 alle 08:35 cagnulein ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
done @bzwolf https://github.com/cagnulein/qdomyos-zwift/actions/runs/9243900768
Google is very slow in these days, reviewing the app on the store, even the beta ones. For this reason, in order to check right now if the patch that I did is right, you can use the android build in the link (check at the bottom of the page in about 1 hour). In order to test it you need first to remove the current QZ version on your phone, install the one that you downloaded.
This version is a 15 minutes trial (you can restart it as many times as you want) and I can unlock it if you want, send me an email to roberto.viola83@gmail.com mentioning this ticket and that you are on android.
Let me know if you have any questions

**Comment by cagnulein** [comment]
@bzwolf are we OK with this?
