### ISSUE TITLE
Healthrider H30X Resistance buttons not working in app. Not seeing all 22 resistance settings[BUG]

### ISSUE THREAD

**Issue by CurtisVermeeren** [cagnulein/qdomyos-zwift#2359]
**Describe the bug**
I am unable to adjust the resistance of a Healthrider H30X using the app. The + and - buttons on the resistance tile do not change the device setting.

When manually adjusting the resistance using the buttons on the machine the reported values in the app do not match.  The machine has resistance 1-22 but the app does not show all values in this range. 

**To Reproduce**
This issue was consistent every time I connected to the machine with the app.

**Expected behavior**
I expected pressing the + and - buttons on the resistance tile of the app would change the resistance on the machine from 1 to 22.

**Smartphone (please complete the following information):**
Google Pixel 7a Android 14

**Append a debug log**

[debug-Tue_May_28_21_13_10_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/15477991/debug-Tue_May_28_21_13_10_2024.log)

[btsnoop_hci.log](https://github.com/cagnulein/qdomyos-zwift/files/15477992/btsnoop_hci.log)  
  
**Additional context**
I think the Healthrider H30x is very similar to the Proform CSX 325 #1602 based on appearance

The Healthrider H30x appears as I_EB in the app.

**Comment by cagnulein** [comment]
Thanks I will check it ASAP

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 29 mag 2024 alle 04:32 Curtis ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
Hi! in the hci snoof did you change the resistance from the ifit app directly? I don't see them.
Let me know!

**Comment by cagnulein** [comment]
Yes because I need to sniff the ifit protocol when you do this
Thanks

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 29 mag 2024 alle ore 14:30 Curtis ***@***.***>
ha scritto:

**Comment by CurtisVermeeren** [comment]
Here is a new log I created using the iFit app to change resistances from 1 to 22. 

[btsnoop_hci.log](https://github.com/cagnulein/qdomyos-zwift/files/15484579/btsnoop_hci.log)

As an aside when I re-paired the bike with the iFit app I noticed it was recognized as a proform 325 csx by the iFit app.

**Comment by cagnulein** [comment]
i almost did everything, i just need the command of the first resistance,
because you started pressing plus but i don't know the first resistance
command. are you able to collect it again going from 1 to 22 and then back
to 1?
Thanks

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 29 mag 2024 alle ore 14:53 Curtis ***@***.***>
ha scritto:

**Comment by CurtisVermeeren** [comment]
I will try the beta version when it's available

**Comment by cagnulein** [comment]
done https://github.com/cagnulein/qdomyos-zwift/actions/runs/9287802209

Google is very slow in these days, reviewing the app on the store, even the beta ones. For this reason, in order to check right now if the patch that I did is right, you can use the android build in the link (check at the bottom of the page in about 1 hour). In order to test it you need first to remove the current QZ version on your phone, install the one that you downloaded.
This version is a 15 minutes trial (you can restart it as many times as you want) and I can unlock it if you want, send me an email to roberto.viola83@gmail.com mentioning this ticket and that you are on android.
Let me know if you have any questions

**Comment by CurtisVermeeren** [comment]
I enabled the Proform CSX 325 / Healthrider H30X profile in the bike options of settings and then the QZ app worked as intended. 

I was able to go from 1 to 22 using the app or the bike controls and both synced properly!

**Comment by cagnulein** [comment]
Amazing!
