### ISSUE TITLE
[BUG] Cadence Dismatch issue among schwinn 270 console, QZ app and Zwift

### ISSUE THREAD

**Issue by Charminghyeok** [cagnulein/qdomyos-zwift#2366]
**Describe the bug**

I confirmed that the cadence does not match on the Zwift, qz, and console of schwinn 270. First of all, even at qz, the cadence value continues to remain at 0. However, the values are appearing in Zwift and schwinn console.

Meanwhile, the values of Zwift and Schwinn's Console match only when the ground is flat, that is, when there is no downhill or uphill slope, and are only applied when the value is below 65. Even if I pedal more than that, the number doesn't go any higher.

Meanwhile, when you go uphill, you can see Zwift's rpm dropping. The difference with the console increases as the slope of the climb becomes steeper. but when going downhill in Zwift, the rpm increases than the console said.

**To Reproduce**
1. connect with schwinn 270 with QZ
2. turn on the computer and turn on the zwift
3. start game (this is the first problem, QZ app does not show cadence)
4. pedaling faster than about 65 ( this is the second problem, it does not go up than around 65 whenever my console say rpm is more than 65, even over 80)
5. following the trank and go to uphill or downhill
6. check the rpm in console and zwift does not match (this is the third problem) 

https://drive.google.com/file/d/1Qph8GBFWtHI8GHUmaYinYCFG7ZsGYrrA/view?usp=sharing

https://drive.google.com/file/d/1f3Bc-drYeUN11lkM5oJST3aYDBJZgvCd/view?usp=sharing

https://drive.google.com/file/d/1vhCL7TMONq0ZfAGUHrCyNqydkm905mRr/view?usp=sharing

https://drive.google.com/file/d/1lAD5Ycpac64csA7eLbQTc_-jeRs_gKwk/view?usp=sharing

**Desktop (please complete the following information):**
 - OS: Windows 11 and/or macOS sonoma both
 - Version win 11 23H2, macOS 14.5 (23F79)

**Smartphone (please complete the following information):**
 - Device: Galaxy S20 + 5g
 - OS: Android 13, Galaxy one UI 5.1
 - Version: Android 13, Galaxy one UI 5.1

**Append a debug log**

 [debug-Sat_Jun_1_13_13_59_2024[1].log](https://github.com/user-attachments/files/15522763/debug-Sat_Jun_1_13_13_59_2024.1.log)
  [debug-Sat_Jun_1_13_14_09_2024[1].log](https://github.com/user-attachments/files/15522764/debug-Sat_Jun_1_13_14_09_2024.1.log)
  
**Additional context**

**Comment by cagnulein** [comment]
Got the issue: join the beta from here
https://play.google.com/apps/testing/org.cagnulen.qdomyoszwift and then
update the app from the store and let me know!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 1 giu 2024 alle 19:47 Charminghyeok ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
ok @Charminghyeok i guess I fixed it

https://github.com/cagnulein/qdomyos-zwift/actions/runs/9363205655

Google is very slow in these days, reviewing the app on the store, even the beta ones. For this reason, in order to check right now if the patch that I did is right, you can use the android build in the link (check at the bottom of the page in about 1 hour). In order to test it you need first to remove the current QZ version on your phone, install the one that you downloaded.
This version is a 15 minutes trial (you can restart it as many times as you want) and I can unlock it if you want, send me an email to roberto.viola83@gmail.com mentioning this ticket and that you are on android.
Let me know if you have any questions

**Comment by cagnulein** [comment]
@Charminghyeok any news?

**Comment by Charminghyeok** [comment]
Nothing problem,
Thank you for considering me
