### ISSUE TITLE
Flow Fitness - DCT2000i

### ISSUE THREAD

**Issue by kevinthijs** [cagnulein/qdomyos-zwift#2403]
**Describe the bug**
Qdomyos connects without problems, but receives no data (see screenshot)

[debug-zo_jun_23_16_49_36_2024.log](https://github.com/user-attachments/files/15945108/debug-zo_jun_23_16_49_36_2024.log)
![IMG_D75E37752EA8-1](https://github.com/cagnulein/qdomyos-zwift/assets/147716953/d9a6eee8-e0f4-49f5-9153-f51060e0f5bf)

**Smartphone (please complete the following information):**
 - Tested on macOS and IOS

**Comment by cagnulein** [comment]
Hi @kevinthijs is it a treadmill or a bike?

**Comment by kevinthijs** [comment]
Forgot to mention, this is a elliptical trainer.
  
​

**Comment by cagnulein** [comment]
Ok I will check this tomorrow

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 23 giu 2024 alle 19:58 kevinthijs ***@***.***>
ha scritto:

>
> Forgot to mention, this is a elliptical trainer.
>
> ​
>

**Comment by cagnulein** [comment]
Hi @kevinthijs do you have also an android device to a test with the iconsole app? I would like to collect some data following this guide https://github.com/cagnulein/qdomyos-zwift/blob/master/docs/20_supported_devices_and_applications.md#android-device

let me know!

**Comment by kevinthijs** [comment]
Got it but message to big. Any idea?

Op ma 24 jun 2024 om 08:23 schreef Roberto Viola ***@***.***>

**Comment by cagnulein** [comment]
you can send me to email to roberto.viola83 at gmail.com or put it to google drive
Let me know!

**Comment by cagnulein** [comment]
i'm attaching here only the bt file received 
[btsnoop_hci (3).zip](https://github.com/user-attachments/files/15953094/btsnoop_hci.3.zip)

**Comment by cagnulein** [comment]
perfect @kevinthijs i will create a patch asap!

**Comment by cagnulein** [comment]
@kevinthijs done!

https://github.com/cagnulein/qdomyos-zwift/actions/runs/9643517710

Google is very slow in these days, reviewing the app on the store, even the beta ones. For this reason, in order to check right now if the patch that I did is right, you can use the android build in the link (check at the bottom of the page in about 1 hour). In order to test it you need first to remove the current QZ version on your phone, install the one that you downloaded.
This version is a 15 minutes trial (you can restart it as many times as you want).
Let me know if you have any questions

**remember to enable the iconsole ellitpical setting under the iconsole settings in QZ**

if it works correctly I will build it also for iOS

Let me know!

**Comment by kevinthijs** [comment]
Roberto,
  
​
  
​Did a quick test and it worked! Small delay, but could be related to android tablet.
  
​
  
​Thx a million for the fast repair.
  
According to the manufacture this device should work out of the box with zwift...​
  
​
  
​
  
​
  
  
  
  
Mvg,
  
​Kevin
  
  

  
​
  
  
  
  
  
  
  
  
  
  
  
  
  

  Dakkofferverhuur.be (http://dakkofferverhuur.be/)
 Kastanjeboomstraat 7
 8550 Zwevegem

**Comment by cagnulein** [comment]
that's great!
