### ISSUE TITLE
New setting for Peloton Low, AVG, High

### ISSUE THREAD

**Issue by cagnulein** [cagnulein/qdomyos-zwift#242]

**Comment by hoveeman** [comment]
This will be great since they call out 80-100 cadence and 35-55 on the resistance. 

Will this essentially do the following based on the number example above?
Low = 80 cadence, 35 resistance 
AVG = 90 cadence, 45 resistance
High = 100 cadence, 55 resistance 

Will this be something you select in the settings, or will you be able to change this mid ride?

I could see benefits to both, but probably easier to set in the settings to start?

**Comment by cagnulein** [comment]
I'm doing it in the settings right now. In realtime you can always change
them by the target resistance tile

Il sab 3 apr 2021, 16:16 hoveeman ***@***.***> ha scritto:

**Comment by hoveeman** [comment]
That’s perfect!
