### ISSUE TITLE
[REQ] Auto adjust running power from Stryd when using a treadmill incline

### ISSUE THREAD

**Issue by ecebear14** [cagnulein/qdomyos-zwift#2437]
**Is your feature request related to a problem? Please describe.**
When changing the incline, the running power should change. Right now the only way to do it is to have a constant power gain, but this doesn't work for workouts when you're changing the incline. 

**Describe the solution you'd like**
A toggle to automatically adjust the gain based on the incline. That way the existing functionality isn't removed

**Describe alternatives you've considered**
None

**Additional context**
It looks like this feature was implemented and then removed: 
https://github.com/cagnulein/qdomyos-zwift/issues/1741
https://github.com/cagnulein/qdomyos-zwift/issues/1765

**Comment by cagnulein** [comment]
@ecebear14 it's still there. Are you on android or ios? On ios is in beta, so maybe that's your issue?
let me know!

**Comment by ecebear14** [comment]
I'm on Android with app version 2.16.55

Is there an option to toggle the gain based on the inclination? I just tried it before creating this and saw that the power on a 20% incline at a given speed is the exact same number as when I run flat outdoors at the same speed.

**Comment by cagnulein** [comment]
just to be sure: are you using your treadmill with QZ and the stryd sensor accessories in the qz settings and also the power sensor as a treadmill is disabled, right?

**Comment by cagnulein** [comment]
ok i will check it asap

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 9 lug 2024 alle 21:10 ecebear14 ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
ok got it now. The code is there but for other type of treadmills. Ok this what i will do: i will revert back the modificaiton https://github.com/cagnulein/qdomyos-zwift/commit/96c80d5bb61d08adb9ef23ba7952260bdff135ef but this time i will put it under setting disabled by default, so that you can enable this in order to have this calculation.

Sounds ok to you?

**Comment by ecebear14** [comment]
That sounds perfect, thank you!

**Comment by cagnulein** [comment]
@ecebear14 done!
https://github.com/cagnulein/qdomyos-zwift/actions/runs/9869751253

I added a new setting in the power sensor section about the inclination gain.

Google is very slow in these days, reviewing the app on the store, even the beta ones. For this reason, in order to check right now if the patch that I did is right, you can use the android build in the link (check at the bottom of the page in about 1 hour). In order to test it you need first to remove the current QZ version on your phone, install the one that you downloaded.
This version is a 15 minutes trial (you can restart it as many times as you want) and I can unlock it if you want, send me an email to roberto.viola83@gmail.com mentioning this ticket and that you are on android.
Let me know if you have any questions

**Comment by ecebear14** [comment]
Just tested the build out and it works perfectly! Thank you so much for the quick fix

**Comment by cagnulein** [comment]
that's great!
