### ISSUE TITLE
Connects to BH Fitness iConcept Boxster Dual but nothing works

### ISSUE THREAD

**Issue by lmarinheira** [cagnulein/qdomyos-zwift#2443]
As described, the app detects the treadmill but nothing happens and the ui wont update if i start the treadmill manually. I'll attach a debug log
[debug-Thu_Jul_11_12_24_49_2024.log](https://github.com/user-attachments/files/16176156/debug-Thu_Jul_11_12_24_49_2024.log)

**Comment by cagnulein** [comment]
Thanks, I will check it later today

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 11 lug 2024 alle 13:34 lmarinheira ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
hi @lmarinheira log checked. Added a patch for your treadmill

https://github.com/cagnulein/qdomyos-zwift/actions/runs/9891793625

I will need several version to adjust the connection with your treadmill since it's bluetooth 2.0, but we will got it, don't worry.

Google is very slow in these days, reviewing the app on the store, even the beta ones. For this reason, in order to check right now if the patch that I did is right, you can use the android build in the link (check at the bottom of the page in about 1 hour). In order to test it you need first to remove the current QZ version on your phone, install the one that you downloaded.
This version is a 15 minutes trial (you can restart it as many times as you want) and I can unlock it if you want, send me an email to roberto.viola83@gmail.com mentioning this ticket and that you are on android.
Let me know if you have any questions

**Comment by lmarinheira** [comment]
Tried the new build on android, same behavior, will connect fine after
enabling TRX Route Key , but nothing works on the panel.

Roberto Viola ***@***.***> escreveu (quinta, 11/07/2024 à(s)
13:54):

**Comment by cagnulein** [comment]
share a fresh debug log

**Comment by lmarinheira** [comment]
Here's the new log

[debug-Thu_Jul_11_17_07_01_2024.log](https://github.com/user-attachments/files/16180489/debug-Thu_Jul_11_17_07_01_2024.log)

**Comment by cagnulein** [comment]
got it https://github.com/cagnulein/qdomyos-zwift/actions/runs/9894934501

**Comment by lmarinheira** [comment]
Tried this last version, same behaviour, here's the new log

[debug-Thu_Jul_11_17_56_03_2024.log](https://github.com/user-attachments/files/16181114/debug-Thu_Jul_11_17_56_03_2024.log)

**Comment by cagnulein** [comment]
Thanks I will check this later

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 11 lug 2024 alle 18:58 lmarinheira ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
check the log. the first time you need to wait some minutes because it has to discover all the services. it requires only the first time.
so please run it again, wait 2 minutes at least and then if you don't see anything, send me a debug log so i can check that it discovered the services
thanks

**Comment by lmarinheira** [comment]
you were right, after 2-3 minutes i was able to power on and off the treadmill from the app. None of the other indicators worked on the app though and everytime i tried to change inclination it would stop the run. ill attach a new log:

[debug-Thu_Jul_11_19_47_08_2024.log](https://github.com/user-attachments/files/16182374/debug-Thu_Jul_11_19_47_08_2024.log)

**Comment by cagnulein** [comment]
ok now i'm out for a nightly walk, good news is that i can see all the frames from the treadmill so we are talking with it! can you try to press start if you didn't already on qz? press pause start to see if it makes any difference. I guess the problem now is that the treadmill thinks that it's in pause mode, So it's sending all the metrics to zero. We have to say with the star button that we are running now.

**Comment by lmarinheira** [comment]
i did, and it starts the treadmill, but there no info on qz either way. The start and pause button works. Also when changing inclination it also stops the treadmill. Nothing happens when trying to change the speed.

**Comment by cagnulein** [comment]
OK, I will check the log tomorrow. 9 o'clock in the evening now here in
Italy. Have a nice evening!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 11 lug 2024 alle 21:04 lmarinheira ***@***.***>
ha scritto:

**Comment by lmarinheira** [comment]
Take your time mate, thanks again for all the time its taking you to check this.

**Comment by cagnulein** [comment]
hi @lmarinheira log checked. could you please create another log where you are taking note what you are doing exactly.
for example, attach me a log where you are doing:
- set the speed from the treadmill directly to 2 km/h
- then set the speed to 5 after 30 seconds
- then the inclination to 5 after 30 seconds

Because in the log I saw something but it's different from the others that I already handled!
Let me know, with these informations I should be able to parse them

**Comment by lmarinheira** [comment]
Sadly i think its not possible to control the treadmill when a connection is made through bluetooth, if i try to click any button nothing happens after this symbol appears on the display

![IMG_2343](https://github.com/user-attachments/assets/3e19f02c-25b0-45c0-a7cd-a1ab0c2e700d)

**Comment by cagnulein** [comment]
ok let's try another thing, could you please enable the "TRX 65s EVO" setting in the toorx settings in qz, and restart it.
Then try to press start on QZ, let's see if we are lucky
Let me know

**Comment by lmarinheira** [comment]
With that option turned on it read some random data on multiple fields, here is the log 

[debug-Sat_Jul_13_11_13_42_2024.log](https://github.com/user-attachments/files/16201808/debug-Sat_Jul_13_11_13_42_2024.log)

**Comment by cagnulein** [comment]
Thanks, I'll check it out.
Currently on a century ride outdoor

Il giorno sab 13 lug 2024 alle 12:21 lmarinheira ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
ok are you able to collect some logs following this https://github.com/cagnulein/qdomyos-zwift/blob/master/docs/20_supported_devices_and_applications.md#android-device from an app that already works with your treadmill? In this way i will clone the behaviour, let me know!

**Comment by cagnulein** [comment]
@lmarinheira any news?
