### ISSUE TITLE
No metrics treadmill doesnt react to app BUG]

### ISSUE THREAD

**Issue by Joeribar** [cagnulein/qdomyos-zwift#2453]
[debug-Mon_Jul_15_20_41_52_2024.log](https://github.com/user-attachments/files/16239076/debug-Mon_Jul_15_20_41_52_2024.log)
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
it seems that your treadmill didn't start at all. did you try to press start on qz?

**Comment by Joeribar** [comment]
Yes that's something strange to soon as I open the app and it connects it start automaticly. Not sure if this how it's supposed to be. But I tried pressing the start button doesn't make a difference

**Comment by cagnulein** [comment]
yes it's supposed to be in this way. did you have always the anyrun setting enabled in the past in the fitshow treadmill setting in qz? you can try to disable and see if it makes any difference.
also did you update the firmware of the treadmill recently?

**Comment by cagnulein** [comment]
this is your original ticket https://github.com/cagnulein/qdomyos-zwift/issues/1663

**Comment by cagnulein** [comment]
i guess i found the issue, it's about this one https://github.com/cagnulein/qdomyos-zwift/commit/717d90b98c93be1915b2a184a669aa65f4337736

**Comment by cagnulein** [comment]
ticket #1950

**Comment by cagnulein** [comment]
@Th3Raven are you still using QZ? i have to add a setting for your treadmill since it's broken the @Joeribar one

**Comment by cagnulein** [comment]
@Joeribar https://github.com/cagnulein/qdomyos-zwift/actions/runs/9945571672
Google is very slow in these days, reviewing the app on the store, even the beta ones. For this reason, in order to check right now if the patch that I did is right, you can use the android build in the link (check at the bottom of the page in about 1 hour). In order to test it you need first to remove the current QZ version on your phone, install the one that you downloaded.
This version is a 15 minutes trial (you can restart it as many times as you want) and I can unlock it if you want, send me an email to roberto.viola83@gmail.com mentioning this ticket and that you are on android.
Let me know if you have any questions

**Comment by cagnulein** [comment]
@Th3Raven if you will use it again, remember to enable the new Athelica setting in the fitshow treadmill setting in qz
