### ISSUE TITLE
[BUG] Not able to change gears using play controller

### ISSUE THREAD

**Issue by Cyberk30** [cagnulein/qdomyos-zwift#2475]
**Describe the bug**
 Not able to change gears using play controller

**To Reproduce**

**Expected behavior**
The gear tile to move up or down using play controller
[debug-Tue_Jul_23_15_45_31_2024.log](https://github.com/user-attachments/files/16354231/debug-Tue_Jul_23_15_45_31_2024.log)
.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: android
 - Version [14]

**Smartphone (please complete the following information):**

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**
Some times the gear tile doesn't show up unless the qz app is paired to the kicker core

**Comment by cagnulein** [comment]
Hi @Cyberk30 log checked. THe problem is that I can't see the zwift play at all. I guess the startup flow is not right, try to follow this:
- first of all be sure that zwift or any other apps is closed
- turn on your bike
- wake up both zwift play
- open qz
- you should see quickly the zwift play in the top label

Let me know

**Comment by cagnulein** [comment]
@Cyberk30 any news?
