### ISSUE TITLE
[REQ]Name device change

### ISSUE THREAD

**Issue by 14Sanchis14** [cagnulein/qdomyos-zwift#2508]
Is there any possibility to change the device name from Wahoo 0000 33 to something like Saris or Xiaomi in the app?

It´s impossible to use 2 devices at same time in my home.

Thanks

**Comment by cagnulein** [comment]
Sure, I'm currently in vacation for the next 2 weeks, I will try my best

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 10 ago 2024 alle 21:01 14Sanchis14 ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
Just sent a new beta: in the experimental settings, you can change the id
of the dircon so it will show a new id in zwift
Let me know!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 10 ago 2024 alle ore 21:06 cagnulein ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
Hah Ok you can download it from here https://github.com/cagnulein/qdomyos-zwift/actions/runs/10349695234

Google is very slow in these days, reviewing the app on the store, even the beta ones. For this reason, in order to check right now if the patch that I did is right, you can use the android build in the link (check at the bottom of the page in about 1 hour). In order to test it you need first to remove the current QZ version on your phone, install the one that you downloaded.
This version is a 15 minutes trial (you can restart it as many times as you want) and I can unlock it if you want, send me an email to roberto.viola83@gmail.com mentioning this ticket and that you are on android.
Let me know if you have any questions

**Comment by 14Sanchis14** [comment]
Alright, I'll try it. I had already bought the regular version for my wife and me, and I am included in Google's beta system.

You are great

Alberto Rodríguez Blas
________________________________

**Comment by 14Sanchis14** [comment]
Sorry i don't know to download the app

Alberto Rodríguez Blas
________________________________
