### ISSUE TITLE
[BUG] not getting emails with workout fit files 

### ISSUE THREAD

**Issue by mazatov** [cagnulein/qdomyos-zwift#2510]
Seems like I stopped getting emails with fit files and syncs with Strava. 

I re logged in with Strava username and password so hopefully it'll work now. But email in the app is indicated correctly. Anything I can do to reactivate that?

**Comment by cagnulein** [comment]
which is your email address that you set on qz? don't send it here because
otherwise github would mask it. send it like roberto.viola83 at gmail.com
so I will check on the server side if i see it
Anyway everything is running ok on the server side, so i suggest to check
the spam folder

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 11 ago 2024 alle ore 16:17 Mike Azatov <
***@***.***> ha scritto:

**Comment by mazatov** [comment]
All working now. What I learned is that I need to click the Stop button, otherwise, if I quit the app directly it won't record anything.

**Comment by cagnulein** [comment]
Yes exactly!
