### ISSUE TITLE
[BUG] QZ calculates calories too low inaccurately.

### ISSUE THREAD

**Issue by saeonnuri** [cagnulein/qdomyos-zwift#2537]
**Describe the bug**
I found this bug when syncing the fit data to Strava for recording into Samsung Health. However, sent fit data all seems fine except too low calories.

When I saw the saved fit file, it saved calories with kCal unit, but it also seems wrong because the 50 min ride would not burn 7000 calories.
[QZ Fit data.zip](https://github.com/user-attachments/files/16739131/QZ.Fit.data.zip)

I attached 50 min ride, short test ride to create log, debug log, and profile data in the above data zip.
The gears I'm using;
1. Old indoor bike without any data sharing functions or modules.
2. M2Me VRFit cadence & power sensor which is used as power sensor in the QZ app. (The sensor can check power value too.)
3. Samsung watch with QZ watch app to get heart rate.
4. Meta quest 3 VZFit app connected
**To Reproduce**

Just ride a few minutes with sensor connected.

**Expected behavior**

Calories must be calculated based on power value and time or heart rate.

**Screenshots**
![strava wrong calories](https://github.com/user-attachments/assets/9900917b-03c2-4ffc-8851-0f54f80d2666)

**Desktop (please complete the following information):**
 Not used to this bug.

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S24
 - OS: One UI 6.1 based on Android 14
 - Version: 2.16.67 (QZ app version, joined Experimental to use Samsung watch as heart rate sensor)

**Append a debug log**
Check log file inside [QZ Fit data.zip](https://github.com/user-attachments/files/16739131/QZ.Fit.data.zip)
  
**Additional context**
Check the 50 min ride fit data(This session does not create debug log) and qz profile data in the zip file.

**Comment by cagnulein** [comment]
got the issue, i will try to fix it today

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 25 ago 2024 alle 08:33 saeonnuri ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
done @saeonnuri https://github.com/cagnulein/qdomyos-zwift/actions/runs/10545260553
Google is very slow in these days, reviewing the app on the store, even the beta ones. For this reason, in order to check right now if the patch that I did is right, you can use the android build in the link (check at the bottom of the page in about 1 hour). In order to test it you need first to remove the current QZ version on your phone, install the one that you downloaded.
This version is a 15 minutes trial (you can restart it as many times as you want) and I can unlock it if you want, send me an email to roberto.viola83@gmail.com mentioning this ticket and that you are on android.
Let me know if you have any questions

**Comment by saeonnuri** [comment]
Hi, Thank you for your supporting.

Calories calculation now seems fine, however now the heart rate from Samsung Watch(Galaxy watch 7) is disabled. Is it normal in the beta version that you've uploaded here?

My QZ WearOS version in Samsung Watch is 1.1.11

**Comment by cagnulein** [comment]
Yes it's because it works only with the official play store app. I will
push it tomorrow and Google will review it in a few days

Join the beta here in the meantime
https://play.google.com/apps/testing/org.cagnulen.qdomyoszwift

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 25 ago 2024 alle 17:19 saeonnuri ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
mmm i didn't push the beta yet, anyway ok the issue is fixed, you will see the update in the beta channel this week hopefully

**Comment by saeonnuri** [comment]
Well, that's curious but it's fixed anyway. Maybe somethings were tangled in my mobile phone about functions related calories. Reinstall and reconfiguring might fix this problem. I'll let you know if it happens again. Thank you for caring this problem.
