### ISSUE TITLE
MyWhoosh not finding anything

### ISSUE THREAD

**Issue by Dwhetsel** [cagnulein/qdomyos-zwift#2598]
**Describe the bug**
Attached is the debug file for trying to connect Mywhoosh to QZ as talked about in our facebook conversation.

[debug-Sun_Sep_15_10_27_19_2024 2.zip](https://github.com/user-attachments/files/17006347/debug-Sun_Sep_15_10_27_19_2024.2.zip)

**Comment by cagnulein** [comment]
You disabled everything in the experimental settings, that's why :)

Enable the virtual device and also virtual Bluetooth device and restart Qz!

Let me know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 15 set 2024 alle 17:40 Dwhetsel ***@***.***> ha
scritto:

**Comment by Dwhetsel** [comment]
After turning those back on (I think I turned them off tying to get it to work) MyWhoosh sees wahoo kicker, wahoo hr, wahoo tread and iphone. The iphone will connect but shows data intermittently and the wahoo kicker does not show any data.

**Comment by cagnulein** [comment]
Did you also enable the mywhoosh compatibility in the experimental settings?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 15 set 2024 alle 20:58 Dwhetsel ***@***.***> ha
scritto:

**Comment by Dwhetsel** [comment]
Oh, no I did not. It is on now and does look to be working. Thank you very much. Have a great day.

**Comment by cagnulein** [comment]
Glad to hear it! Remember to support QZ on patreon if you can! https://www.patreon.com/cagnulein
