### ISSUE TITLE
Renpho AI Smart Bike: no metrics

### ISSUE THREAD

**Issue by Ceiken22** [cagnulein/qdomyos-zwift#2644]
**Describe the bug**
When connected to renpho ai smart bike there is no stats on qz when pedaling. 

**To Reproduce**
1. Connect to renpho ai bike. 
2. Pedal

**Expected behavior**
Stats are supposed to be recognized while pedaling. 

**Screenshots**

**Desktop (please complete the following information):**
 

**Smartphone (please complete the following information):**
 Tmobile revvl 5g

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**
I did the bug report but I'm not sure what to do with the file.

**Comment by cagnulein** [comment]
Thanks, but I don't see the debug log. Please attach it
I'm going to bed now, I will check it tomorrow 
Thanks

**Comment by Ceiken22** [comment]
It says I am not able to access the android data file due to privacy
reasons.

**Comment by cagnulein** [comment]
enable the android document setting in the experimental settings and qz will save the log under /documents/qz

let me know

**Comment by Ceiken22** [comment]
_![debug-Fri_Oct_11_04_00_51_2024.log](https://github.com/user-attachments/files/17340765/debug-Fri_Oct_11_04_00_51_2024.log)

**Comment by cagnulein** [comment]
hi @Ceiken22 I guess I already fixed this on the #2401 
could you please give a test to https://github.com/cagnulein/qdomyos-zwift/releases/download/nightly/android-debug.apk

Google is very slow in these days, reviewing the app on the store, even the beta ones. For this reason, in order to check right now if the patch that I did is right, you can use the android build in the link (check at the bottom of the page in about 1 hour). In order to test it you need first to remove the current QZ version on your phone, install the one that you downloaded.
This version is a 15 minutes trial (you can restart it as many times as you want) and I can unlock it if you want, send me an email to roberto.viola83@gmail.com mentioning this ticket and that you are on android.
Let me know if you have any questions
