### ISSUE TITLE
Start and stop Kingsmith X23 (KS-NACH-MXG)

### ISSUE THREAD

**Issue by fre-bod** [cagnulein/qdomyos-zwift#2645]
Hi, I got a Kingsmith X23 (KS-NACH-MXG). I can change the speed successfully from the app but I wonder if it is possible to stop and start the treadmill from the app in some way? 

[debug-Thu_Oct_10_18_17_49_2024.log](https://github.com/user-attachments/files/17333793/debug-Thu_Oct_10_18_17_49_2024.log)

**Comment by cagnulein** [comment]
Thanks I will check it!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 10 ott 2024 alle 22:25 fre-bod ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
we started this here https://github.com/cagnulein/qdomyos-zwift/pull/813

**Comment by cagnulein** [comment]
@fre-bod ok i did a raw implementation

https://github.com/cagnulein/qdomyos-zwift/actions/runs/11288257785

Google is very slow in these days, reviewing the app on the store, even the beta ones. For this reason, in order to check right now if the patch that I did is right, you can use the android build in the link (check at the bottom of the page in about 1 hour). In order to test it you need first to remove the current QZ version on your phone, install the one that you downloaded.
This version is a 15 minutes trial (you can restart it as many times as you want) and I can unlock it if you want, send me an email to roberto.viola83@gmail.com mentioning this ticket and that you are on android.
Let me know if you have any questions

**Comment by fre-bod** [comment]
@cagnulein 
I have now tested and can confirm that it works, thank you!

Will you update the official app in Play Store (I don't want to have the Android "install unknown apps" setting enabled)?

**Comment by cagnulein** [comment]
Glad it worked!
yes i will push into the beta in the next days

Il giorno ven 11 ott 2024 alle 21:42 fre-bod ***@***.***> ha
scritto:
