### ISSUE TITLE
[BUG] zonehr="0" ignored from xml training program file

### ISSUE THREAD

**Issue by lorenzogavanna** [cagnulein/qdomyos-zwift#2703]
The app won't change the zone when in the xml zonehr parameter is 0

1. Load the xml training program (you can find it attached here)
2. Run it
3. the PID zone will not change to 0

It should change between all the zones you set 0 (free) included.

- OS: Xiaomi Mi Lite 5G
- Mobvoi Home Treadmill Plus
- QZ app 2.18.1
 log and xml (txt format unless i will not be able to upload it) attached.

[testhr.txt](https://github.com/user-attachments/files/17534167/testhr.txt)
[debug-Sun_Oct_27_14_49_47_2024.log](https://github.com/user-attachments/files/17534166/debug-Sun_Oct_27_14_49_47_2024.log)

**Comment by cagnulein** [comment]
Thanks I will check it ASAP

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 27 ott 2024 alle 15:00 lorenzogavanna <
***@***.***> ha scritto:

**Comment by cagnulein** [comment]
@lorenzogavanna fixed

https://github.com/cagnulein/qdomyos-zwift/actions/runs/11552090258

Google is very slow in these days, reviewing the app on the store, even the beta ones. For this reason, in order to check right now if the patch that I did is right, you can use the android build in the link (check at the bottom of the page in about 1 hour). In order to test it you need first to remove the current QZ version on your phone, install the one that you downloaded.
This version is a 15 minutes trial (you can restart it as many times as you want) and I can unlock it if you want, send me an email to roberto.viola83@gmail.com mentioning this ticket and that you are on android.
Let me know if you have any questions

**Comment by lorenzogavanna** [comment]
Works perfectly!! Thank you, report closed. Amazing as always!!

**Comment by cagnulein** [comment]
Hah it could be, let me check this!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 28 ott 2024 alle 13:14 lorenzogavanna <
***@***.***> ha scritto:

**Comment by cagnulein** [comment]
solved!

https://github.com/cagnulein/qdomyos-zwift/actions/runs/11554094836

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 28 ott 2024 alle ore 13:15 cagnulein ***@***.***> ha
scritto:
