### ISSUE TITLE
I'm unable to connect my EXERCYCLE H9365R V2 BH correctly. 

### ISSUE THREAD

**Issue by MiguelHerrero73** [cagnulein/qdomyos-zwift#2727]
When I connect QZ on my Android 14 phone to Zwift with my EXERCYCLE H9365R V2 BH, the incline of the slopes my avatar encounters on a route isn't reflected

Without the QZ app, my EXERCYCLE H9365R V2 BH only allows me to adjust resistance by 6 levels from the value sent by Zwift. For example, if I'm at resistance level 17 (out of 24), I can only go up to 23 or down to 11.

QZ allows me to adjust the resistance up or down by any amount, but for some reason, it doesn't accurately reflect the incline of the slope. In fact, it seems like it's not reflecting any incline at all.

Phone: Galaxy S24 Ultra. Android 14. Samsung UI 6.1
Zwift runs on a Galaxy Tab S8 Ultra. Android 14. Samsung UI 6.1

I have attached the .log and .fit files from that session from de QZ app
[debug-Sat_Nov_2_15_54_42_2024.log](https://github.com/user-attachments/files/17607429/debug-Sat_Nov_2_15_54_42_2024.log)

**Comment by MiguelHerrero73** [comment]
I forgot to mention that I was using the beta version 2.18.1 of QZ

**Comment by cagnulein** [comment]
Got the reason because qz is identifying it as an elliptical. I will do a
patch in the next days for it!
Thanks for the feedback!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 2 nov 2024 alle 16:24 MiguelHerrero73 <
***@***.***> ha scritto:

**Comment by MiguelHerrero73** [comment]
Thanks a lot for being so quick and helpful.
I can't wait to try the patch :-)

**Comment by cagnulein** [comment]
done @MiguelHerrero73  !

https://github.com/cagnulein/qdomyos-zwift/actions/runs/11645024943

set the ftms bike setting in this build for your bike and press ok and restart qz

Google is very slow in these days, reviewing the app on the store, even the beta ones. For this reason, in order to check right now if the patch that I did is right, you can use the android build in the link (check at the bottom of the page in about 1 hour). In order to test it you need first to remove the current QZ version on your phone, install the one that you downloaded.
This version is a 15 minutes trial (you can restart it as many times as you want) and I can unlock it if you want, send me an email to roberto.viola83@gmail.com mentioning this ticket and that you are on android.
Let me know if you have any questions

**Comment by cagnulein** [comment]
@MiguelHerrero73 Are we OK with this?

**Comment by MiguelHerrero73** [comment]
Hi, good morning. Yes, it’s all good. I’ve tried it on Zwift, MyWhoosh, and Training Peaks Virtual (ex-Indievelo). The BH Exercycle works well with those programs, but it only allows you to lower the resistance by 6 levels in simulation mode. With QZ, you’re free to lower the resistance as much as you want :-) Great app, Roberto.

**Comment by cagnulein** [comment]
Amazing!
