### ISSUE TITLE
[BUG] Zwift gear 4 does not change QZ gear or resistance

### ISSUE THREAD

**Issue by raptuz-na** [cagnulein/qdomyos-zwift#2746]
**Describe the bug**

When using Zwift clicker paired to Zwift:

Zwift gear 4 does not change QZ gear or resistance.
Zwift gear 3-1 all have resistance 0.

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy s24 Ultra
 - OS: Android 14
 

[debug-Wed_Nov_6_14_09_45_2024.log](https://github.com/user-attachments/files/17647793/debug-Wed_Nov_6_14_09_45_2024.log)

**Comment by cagnulein** [comment]
fixed! https://github.com/cagnulein/qdomyos-zwift/actions/runs/11704791414

**Comment by cagnulein** [comment]
Google is very slow in these days, reviewing the app on the store, even the beta ones. For this reason, in order to check right now if the patch that I did is right, you can use the android build in the link (check at the bottom of the page in about 1 hour). In order to test it you need first to remove the current QZ version on your phone, install the one that you downloaded.
This version is a 15 minutes trial (you can restart it as many times as you want) and I can unlock it if you want, send me an email to roberto.viola83@gmail.com mentioning this ticket and that you are on android.
Let me know if you have any questions

**Comment by raptuz-na** [comment]
Thanks, this fixed the Zwift gear 4 issue!
I'm just wondering if the gears tile now is supposed to shift gears also in Zwift, or only in QZ, to adjust the offset between them?

**Comment by cagnulein** [comment]
in this scenario, qz is slave and zwift is the master, so the gears are coming directly from zwift.
if otherwise you want to do the viceversa, you have to use the "show gears on zwift only" and connect your click or play or other device to qz to change gears
