### ISSUE TITLE
[BUG] Echelon Rower Sport 2, not displaying stats

### ISSUE THREAD

**Issue by MattinNC** [cagnulein/qdomyos-zwift#2749]
**Describe the bug**
The QZ apps connects to the rower but when rowing does not display any stats. Tested on phone running Android 14 with both stable and beta apps. The rower is found under Rower Options and Virtual Rower is enabled under Experimental Features.

Also installed the Beta app on a tablet running version 11 of android OS, same behavior. The installed the Echelon App and it did display the stats.

![Screenshot_20241106_145438_Echelon Fit](https://github.com/user-attachments/assets/68182d0d-370f-4fb9-948f-b4c2b9c51da1)

QZ version: 2.18.1 - Android

**To Reproduce**
1. start QA App
2. Click on Start
3. Stat rowing
4. No stats displayed 

**Expected behavior**
Expecting the apps to show strokes, etc.

**Screenshots**
![Screenshot_20241106_144318](https://github.com/user-attachments/assets/6e9cf509-ec71-4de4-9d2d-36eff4a27df6)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: Samsung Flip5
 - OS: [Andriod]
 - Version [14]

**Append a debug log**

[debug-Wed_Nov_6_14_20_25_2024.log](https://github.com/user-attachments/files/17652271/debug-Wed_Nov_6_14_20_25_2024.log)

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**
I've read over all the Facebook posts on similar issues  I could find as well as here in Github but the only suggestion was to enable the Virtual Row setting and restart the app. I've done this multiple times but nothing has solved the issue.

**Comment by cagnulein** [comment]
@MattinNC Thanks

Disable the ftms rower and press OK and then install this

https://github.com/cagnulein/qdomyos-zwift/actions/runs/11711017467


Google is very slow in these days, reviewing the app on the store, even the beta ones. For this reason, in order to check right now if the patch that I did is right, you can use the android build in the link (check at the bottom of the page in about 1 hour). In order to test it you need first to remove the current QZ version on your phone, install the one that you downloaded.
This version is a 15 minutes trial (you can restart it as many times as you want) and I can unlock it if you want, send me an email to roberto.viola83@gmail.com mentioning this ticket and that you are on android.
Let me know if you have any questions

**Comment by MattinNC** [comment]
Roberto,

This worked! I did not make any changes to the app, removed the existing
app and installed this and it is now getting the stats! I am using the QZ
app on a phone running android 14.

Thanks so much for your help and quick response!

- Matt
- ***@***.***

**Comment by cagnulein** [comment]
That's great! Remember to send me an email to unlock it mentioning this
