### ISSUE TITLE
[BUG] Auto Resistance doesn't work on Tacx Neo 2T and Peloton App

### ISSUE THREAD

**Issue by matnonio** [cagnulein/qdomyos-zwift#2767]
**Describe the bug**

**To Reproduce**
1. Start Peloton App
2. Start QZ
3. Start class in Peloton app cycling
4. Wait until warmup is done
5. Start QZ Tracking

**Expected behavior**
Auto-resistance should follow the class but it doesn't.

**Smartphone (please complete the following information):**
Android 15 QPR1 beta 3

**Append a debug log**
Attached
  
**Additional context**
Sometimes I'll see the resistance change in the start of the class but then it won't track after that. Tried the AI auto resistance function but that didn't work.

Double checked my login info was correctly entered in Peloton settings section. Looks good and I'm prompted in QZ when the class starts in the Peloton app.

**Comment by cagnulein** [comment]
Hi @matnonio I don't see the log, please attach it as a new comment here. Thanks

**Comment by matnonio** [comment]
[debug-Mon_Nov_11_05_04_56_2024.zip](https://github.com/user-attachments/files/17718767/debug-Mon_Nov_11_05_04_56_2024.zip)

**Comment by cagnulein** [comment]
hi, the problem of this log is that the peloton API wasn't answering at
all. It could be a glitch of the peloton server. Did you already did
another try? did you try also with a class at least 1month old just to
avoid the issue that peloton didn't push the metrics for fresh workouts?
Let me know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 12 nov 2024 alle ore 16:29 mantonio ***@***.***>
ha scritto:

**Comment by matnonio** [comment]
I tried again with a class that's older than 1 month.

The resistance change in the beginning of the class it did not track it after it changed.

Here's a screenshot and the debug log.
[debug-Tue_Nov_12_12_30_45_2024.log](https://github.com/user-attachments/files/17720652/debug-Tue_Nov_12_12_30_45_2024.log)
![Screenshot_20241112-123536](https://github.com/user-attachments/assets/bf077a08-a56f-4320-b7d8-bd75d4f6d9ac)

**Comment by cagnulein** [comment]
Ok perfect now I can see the peloton connection. I will check the problem
tomorrow (7pm here In Italy)

Thanks

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 12 nov 2024 alle 18:41 mantonio ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
thanks @matnonio i deeply check it and unfortunately i can't find the root cause of it. It's the first time that I don't see a clear reason for such a bug.
In order to help you I would like to add some debug log to QZ in order to understand the reason.

https://github.com/cagnulein/qdomyos-zwift/actions/runs/11813804103

Google is very slow in these days, reviewing the app on the store, even the beta ones. For this reason, in order to check right now if the patch that I did is right, you can use the android build in the link (check at the bottom of the page in about 1 hour). In order to test it you need first to remove the current QZ version on your phone, install the one that you downloaded.
This version is a 15 minutes trial (you can restart it as many times as you want) and I can unlock it if you want, send me an email to roberto.viola83@gmail.com mentioning this ticket and that you are on android.
Let me know if you have any questions

**Comment by matnonio** [comment]
I tried to install the APK from the link you provided but got this error.

![Screenshot_20241113-184434](https://github.com/user-attachments/assets/f9b86012-a9fb-4b57-bd02-8613a5a8761b)

**Comment by cagnulein** [comment]
Did you remove first the actual qz version?

**Comment by matnonio** [comment]
Okay thanks, uninstalling the app first worked. Here's the debug log.

[debug-Thu_Nov_14_07_47_53_2024.log](https://github.com/user-attachments/files/17748851/debug-Thu_Nov_14_07_47_53_2024.log)

**Comment by cagnulein** [comment]
ok perfect now i can see the issue: the speed after 5 seconds it was at 0. Did you stop voluntarily to ride? can you please ride a little more? at least for 126 seconds for this class so you will see the next resistance step change. Thanks

**Comment by cagnulein** [comment]
yes you can enable the continuos moving setting to fix this!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 15 nov 2024 alle ore 14:35 mantonio ***@***.***>
ha scritto:

**Comment by matnonio** [comment]
Fixed
