### ISSUE TITLE
[BUG] Pause button on qz won't reset the speed tile

### ISSUE THREAD

**Issue by lorenzogavanna** [cagnulein/qdomyos-zwift#2781]
**Describe the bug**

1. Press start btn
2. set a decent speed (in order to make it not too long)
3. Press pause btn
4. speed tile won't go to 0
5. odometer will keep goin 

The treadmill stops and stays in pause mode properly. Everything in the fit file seems to be correct. 
The odometer should pause since nothing is running and the speed tile should go to 0.

OS: G7 thinkQ - Android 10
Mobvoi Home Treadmill Plus
QZ app 2.18.1
debug log attached.

[debug-Thu_Nov_14_15_55_20_2024.log](https://github.com/user-attachments/files/17750770/debug-Thu_Nov_14_15_55_20_2024.log)

**Comment by cagnulein** [comment]
@lorenzogavanna done!
https://github.com/cagnulein/qdomyos-zwift/actions/runs/11840525088
Google is very slow in these days, reviewing the app on the store, even the beta ones. For this reason, in order to check right now if the patch that I did is right, you can use the android build in the link (check at the bottom of the page in about 1 hour). In order to test it you need first to remove the current QZ version on your phone, install the one that you downloaded.
This version is a 15 minutes trial (you can restart it as many times as you want) and I can unlock it if you want, send me an email to roberto.viola83@gmail.com mentioning this ticket and that you are on android.
Let me know if you have any questions

**Comment by cagnulein** [comment]
i just don't update the distance, i didn't touch the speed value

**Comment by lorenzogavanna** [comment]
Oh I see, didn't think about that!! Stick to your settings, safety first!! eheh  
I close this bug report since everthing now works properly. Thank you again Roberto!
