### ISSUE TITLE
[BUG] Program doesnt work with CardioPower Ergo 5

### ISSUE THREAD

**Issue by Daeamon** [cagnulein/qdomyos-zwift#2804]
**Describe the bug**
According to the seller and the official reseller's website, my elliptical trainer supports programs such as Zwift and kinomap. I have fully configured the program settings for my elliptical trainer according to the wizard. But the program does not connect to it, although it sees it.

**Smartphone (please complete the following information):**
 - Device: Huawei P60 Pro
 - OS: Android
 - Version EMUI 13.1.0

**Append a debug log**
[debug-Wed_Nov_20_14_44_29_2024.log](https://github.com/user-attachments/files/17830681/debug-Wed_Nov_20_14_44_29_2024.log)
[debug-Wed_Nov_20_14_41_01_2024.log](https://github.com/user-attachments/files/17830682/debug-Wed_Nov_20_14_41_01_2024.log)

**Comment by cagnulein** [comment]
Hi could you please download the free app nrfconnect and show me a
screenshot about it from this app? Let me know!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 20 nov 2024 alle 13:47 Daeamon ***@***.***> ha
scritto:

**Comment by Daeamon** [comment]
> Hi could you please download the free app nrfconnect and show me a screenshot about it from this app? Let me know!

![Screenshot_20241120_160108_no nordicsemi android mcp](https://github.com/user-attachments/assets/9ae5d1ea-5138-4cc4-aaac-38335791d855)
![Screenshot_20241120_160142_no nordicsemi android mcp](https://github.com/user-attachments/assets/b8f86d5e-af84-451f-99b7-cf7b58893d94)

**Comment by cagnulein** [comment]
Perfect you can set the trainer under the settings, bike options, ftms bike
and press OK
Let me know if it works correctly!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 20 nov 2024 alle 14:04 Daeamon ***@***.***> ha
scritto:

**Comment by Daeamon** [comment]
> Perfect you can set the trainer under the settings, bike options, ftms bike and press OK Let me know if it works correctly!

Now The device is connected, but there is no data. 
[debug-Wed_Nov_20_16_10_40_2024.log](https://github.com/user-attachments/files/17831133/debug-Wed_Nov_20_16_10_40_2024.log)

**Comment by Daeamon** [comment]
> Are you sure you uploaded the correct file?

Sorry, I restarted the app and the elliptical trainer and everything worked, thanks)

**Comment by cagnulein** [comment]
hah ok i also added using the crosstrainer profile 

https://github.com/cagnulein/qdomyos-zwift/actions/runs/11934330099

Google is very slow in these days, reviewing the app on the store, even the beta ones. For this reason, in order to check right now if the patch that I did is right, you can use the android build in the link (check at the bottom of the page in about 1 hour). In order to test it you need first to remove the current QZ version on your phone, install the one that you downloaded.
This version is a 15 minutes trial (you can restart it as many times as you want) and I can unlock it if you want, send me an email to roberto.viola83@gmail.com mentioning this ticket and that you are on android.
Let me know if you have any questions

you need to disable it from the ftms bike to test this
let me know!

**Comment by Daeamon** [comment]
> crosstrainer profile

Yes, now its work ) thnx
