### ISSUE TITLE
[REQ] Change speed or PID when a workouts is load an is running

### ISSUE THREAD

**Issue by lorenzogavanna** [cagnulein/qdomyos-zwift#2813]
Not a problem at all, just a request.

Let's say I'm running a workout, that I load with qz, and I want to push more that the workout is asking (i.e. current is hr zone 2 --> I want to go to zone 3) or I feel tired and I want to go little slower. I would like to be able to change speed or PID and not that the workout settings are mandatory.

**Describe alternatives you've considered**
I tried to use the treadmill remote to change the speed, but qz forces the speed back to the workout section settings. Even with tiles +/- won't change the output for PID or SPEED.

**Additional context**
I tried only with zwo or xml didn't try with other formats.

**Comment by cagnulein** [comment]
Target speed does already this and shows the percentage

Let me know!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 22 nov 2024 alle 16:18 lorenzogavanna <
***@***.***> ha scritto:

**Comment by lorenzogavanna** [comment]
Ah perfect thank you, so you can do from that tile and not directly from the treadmill. That's why! Thank you. The PID change is still not available right? Thank you!!

**Comment by cagnulein** [comment]
Yes there is also the pid heart tile to change it on runtime! Let me know!

**Comment by lorenzogavanna** [comment]
I know that tile but if I push +/- on that during a hr workout section from xml with it won't change it. It does when no workouts are load.

**Comment by cagnulein** [comment]
Hah Ok so you want override the pid hr value from the tile during a workout
that has pid hr, right? Yes I can add this!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 23 nov 2024 alle 10:18 lorenzogavanna <
***@***.***> ha scritto:

**Comment by lorenzogavanna** [comment]
Yes, just in case if I want to push the workout. And if it's possible override the speed as well not only with the %speed tile, but also at least with the treadmill speed I'm changing, if you think it's worth it.

**Comment by cagnulein** [comment]
With the speed of course if it doesn't have a pid hr in progress

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 23 nov 2024 alle 10:42 lorenzogavanna <
***@***.***> ha scritto:

**Comment by lorenzogavanna** [comment]
yes yes of course, if you have a PID that's the priority! Than if you have a workout my request (again if you think that is ok) is to have control of it, with PID +/-, and with the speed even in zwo power zones based workouts in order to push as much as you want.

**Comment by cagnulein** [comment]
ok @lorenzogavanna i started with the pidhr plus and minus during a workout modification
https://github.com/cagnulein/qdomyos-zwift/actions/runs/12005348750
Google is very slow in these days, reviewing the app on the store, even the beta ones. For this reason, in order to check right now if the patch that I did is right, you can use the android build in the link (check at the bottom of the page in about 1 hour). In order to test it you need first to remove the current QZ version on your phone, install the one that you downloaded.
This version is a 15 minutes trial (you can restart it as many times as you want) and I can unlock it if you want, send me an email to roberto.viola83@gmail.com mentioning this ticket and that you are on android.
Let me know if you have any questions

**Comment by lorenzogavanna** [comment]
Thank you so much for your work Roberto!!
