### ISSUE TITLE
[BUG] Kickr Climb not move

### ISSUE THREAD

**Issue by Ziozanna** [cagnulein/qdomyos-zwift#2823]
**Describe the bug**
My setup, PC, MyWhoosh , QZFitness, Kickr Core, Kickr Climb
I bought QZ to have virtual shifting available on MYWhoohs
Running MyWhooHs linked to my S24 as power source it is preatty working as expected rather than the kickr Climb that is completelly motionless. Same session , just change the power source to Kickr Core, the climb return to work flawlessy.

**To Reproduce**
easy , just try with kickr Climb

**Expected behavior**
Kickr Climb elevate o descend ad in a direct link with kickr core as power source

**Screenshots**
NA

**Desktop (please complete the following information):**
 - Window 11
 - Mywhoohs 3.8.5

**Smartphone (please complete the following information):**
 - Device: [Samsung S24]
 - OS: Android 14 kernel 6.1.75-android-14-11
 - QZapp 2.18.16

**Append a debug log**
NA
 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**
NA

Thanks for the help

**Comment by cagnulein** [comment]
hi @Ziozanna the climb is taking by ant+ the inclination from the core as far as i know. if you pair the core to qz and qz and controllable on mywhosh, everything should work. did you do so? please share a debug log otherwise https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F

**Comment by Ziozanna** [comment]
I did that exactly as you describe.
Problem is that mywhoohs does not control the climb but is the Kickr core that is link to the climb and send the elevation data based on gradient info from the whoohs inclination and weelbase.
In this case looks that the inclination data are not passed to the Kickr core so no movement are imposed to the climb.
If you need more info we can place a call, im italian too

**Comment by cagnulein** [comment]
i guess i understood the issue 
use this apk https://github.com/cagnulein/qdomyos-zwift/releases/download/nightly/android-debug.apk instead
it will be on the play store in the next days but you can test right now in the meantime
In order to test it you need first to remove the current QZ version on your phone, install the one that you downloaded.
This version is a 15 minutes trial (you can restart it as many times as you want) and I can unlock it if you want, send me an email to roberto.viola83@gmail.com mentioning this ticket and that you are on android.
Let me know if you have any questions

**Comment by Ziozanna** [comment]
In the beta version, the Kickr Climb is moving but is affected by the virtual gear position. Adding a gear makes it climb, and subtracting a gear makes it descend. Another flaw is that, in this version, the gear range does not reflect the gear table set in the bike options, and it goes up and down without limits.

**Comment by cagnulein** [comment]
Yes it is expected : with the zwift gear experimental setting under the
accessories disabled you have infinite gears and the clilmb will move
accordingly with the gears

With that enabled (it's experimental so it could not work yet for you) you
should have both the previous one fixed

Let me know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 25 nov 2024 alle 12:54 Ziozanna ***@***.***> ha
scritto:

**Comment by Ziozanna** [comment]
Thanks, Roberto, for your quick support. 
Unfortunately, with 'Use Zwift all ratio for gear' set to ON, the gear range is respected but neither Kr Climb nor Kr Core resistance react accordingly to the elevation.

**Comment by cagnulein** [comment]
yes as I said it's experimental. it's working on iOS but it seems there is some issue on android. Use it with this disabled until i will figure it out.

**Comment by Ziozanna** [comment]
I'll wait for your fix in the mean time i revert to manual gear. 
Not usable with this behaviour

**Comment by cagnulein** [comment]
so are you using it with that setting disabled? or you are now using it with qz? was the previous version better for you?

**Comment by cagnulein** [comment]
ok but you didn't answer to my last comment: was the previous version worked better for you?

**Comment by Ziozanna** [comment]
Sorry about that. 
Neither https://github.com/cagnulein/qdomyos-zwift/releases/download/nightly/android-debug.apk nor QZapp 2.18.16 are improving. 

I will go with the native MyWhoosh until QZ is fixed. 

Thanks.

**Comment by cagnulein** [comment]
@Ziozanna if you have time and you want to make some experiments with me, i tried to clean the init phase here https://github.com/cagnulein/qdomyos-zwift/actions/runs/12013900828

Google is very slow in these days, reviewing the app on the store, even the beta ones. For this reason, in order to check right now if the patch that I did is right, you can use the android build in the link (check at the bottom of the page in about 1 hour). In order to test it you need first to remove the current QZ version on your phone, install the one that you downloaded.
This version is a 15 minutes trial (you can restart it as many times as you want) and I can unlock it if you want, send me an email to roberto.viola83@gmail.com mentioning this ticket and that you are on android.
Let me know if you have any questions

Any feedback will be crucial because I don't have your trainer so i can fix this only with the help of users like you

**Comment by cagnulein** [comment]
[btsnoop_hci_202411260855.zip](https://github.com/user-attachments/files/17915509/btsnoop_hci_202411260855.zip)
just for reference @Ziozanna in this file what you did?
