### ISSUE TITLE
[REQ] (Zwift) Inclination Gain implementation in QZ for Elite Suito/Rouvy

### ISSUE THREAD

**Issue by seders98** [cagnulein/qdomyos-zwift#2850]
**Is your feature request related to a problem? Please describe.**
Changes in gradient (in Rouvy) cause large changes in resistance requiring constant gear changing.
The 'Zwift Inclination Gain' in QZ does not affect the resistance
I am using QZ between Elite Suito trainer and Rouvy virtual platform. 

**Describe the solution you'd like**
Would like to moderate (scale) the change in resistance sent to the trainer when there is a change in gradient in Rouvy. This would mimic the 'trainer difficulty' option that is implemented in Zwift

**Describe alternatives you've considered**
Within the QZ app - change 'Zwift Inclination Gain' but that has no effect
Virtual gears help, but ridability is still poor

**Additional context**
recent log attached
[debug-Sat_Nov_30_15_56_22_2024.log](https://github.com/user-attachments/files/17966059/debug-Sat_Nov_30_15_56_22_2024.log)

**Comment by Ziozanna** [comment]
I have a similar situation. In MYWHOOSH, if you set the gradient to 50%, for example, an 8% climb is sent to the trainer as 4%. On QZ, you see 4%. I imagine the trainer makes the necessary calculations to increase the resistance. 

On descents, it seems to divide by 2 or 3 and then correct with the gradient. An 8% descent with the gradient set to 50% is sent as 2%, and it doesn't go beyond 2% in descents.

My suggestion, using QZ as an interface between the simulator and the trainer to control virtual shifting, incline, power, and heart rate, would be to set the gradient to 100% on MW/ZW/RY/BK, etc., and let QZ handle all the calculations with its own gradient parameter. Otherwise, each app behaves differently and a double conversion creates confusion.

Make sense?

**Comment by cagnulein** [comment]
@seders98 What do you think about @Ziozanna thoughts?

**Comment by seders98** [comment]
On Rouvy there is no option to 'set the gradient to 50%', so I'm not sure how this would be done on Rouvy? There is a 'reality level' which adjusts the gradient sent to the trainer, but this is not available in many rides (e.g. group rides) and makes you go up the hill twice as fast! 

> My suggestion, using QZ as an interface between the simulator and the trainer to control virtual shifting, incline, power, and heart rate, would be to set the gradient to 100% on MW/ZW/RY/BK, etc., and let QZ handle all the calculations with its own gradient parameter. Otherwise, each app behaves differently and a double conversion creates confusion.
> 

I think this is the idea - have QZ adjust the trainer resistance so that you don't have to change gear so often (whilst retaining virtual gears) - the power to MW/ZW/RY/BK would remain unchanged, as would the gradient/speed that you go at on those apps. [I had assumed that this was what the Zwift Inclination Gain did, but it doesn't affect anything on my setup]. I'm not sure if QZ needs it's own gradient parameter, or just adjusts the resistance (due to my lack of knowledge about how all the calculations are done)

**Comment by cagnulein** [comment]
> On Rouvy there is no option to 'set the gradient to 50%', so I'm not sure how this would be done on Rouvy? There is a 'reality level' which adjusts the gradient sent to the trainer, but this is not available in many rides (e.g. group rides) and makes you go up the hill twice as fast!

yes on rouvy it's the reality level, that, as zwift does, send only a portion of the gradient to the trainer. of course the player will generate less wattage.

BUT i just checked the code and the zwift inclination gain should already does this, did you try @seders98 and @Ziozanna  ?
I mean the on in treadmill settings. If it's ok i will move to the advanced settings to be more general

Let me know!

**Comment by seders98** [comment]
Thanks @cagnulein - I tried the zwift inclination gain with my Elite Suito trainer (not treadmill) and it made no difference to the resistance I felt going up the hills. I tried values of 0.5 and 0.3, which should have reduced the resistance significantly.

**Comment by cagnulein** [comment]
hah sorry I figured it out why! it changed the inclination tile but not the inclination on the trainer! let me try to do the patch!

**Comment by cagnulein** [comment]
done @seders98 https://github.com/cagnulein/qdomyos-zwift/actions/runs/12121395663

Google is very slow in these days, reviewing the app on the store, even the beta ones. For this reason, in order to check right now if the patch that I did is right, you can use the android build in the link (check at the bottom of the page in about 1 hour). In order to test it you need first to remove the current QZ version on your phone, install the one that you downloaded.
This version is a 15 minutes trial (you can restart it as many times as you want) and I can unlock it if you want, send me an email to roberto.viola83@gmail.com mentioning this ticket and that you are on android.
Let me know if you have any questions

**Comment by seders98** [comment]
Thanks @cagnulein - I'll hopefully try that this evening and let you know 👍

**Comment by seders98** [comment]
@cagnulein - that looks to work nicely (without doing extensive tests) 
Now the change in resistance is attenuated compared to the normal Rouvy changes.
Many thanks.

**Comment by cagnulein** [comment]
Glad to hear it!


Il giorno lun 2 dic 2024 alle 23:22 Andrew Sederman <
***@***.***> ha scritto:

**Comment by cagnulein** [comment]
Let me know in the next days so I can merge it if it's all ok

**Comment by seders98** [comment]
I probably won't be on the trainer for a few days, but I'll let you know when I try it further - worked well for a short ride yesterday evening, though 👍

**Comment by cagnulein** [comment]
ok i guess i will merge it so, the code was quite simply. thanks

**Comment by Ziozanna** [comment]
I did also intesive test and with kickr core and kickr Climb with mywhoohs , gradiend feel 100% and QZ set to 50% ant it works flawlessy.
BTW my expectation is that on the Inclination tile QZ shows the correct gradient received from the app to match what is on app screen and within the same tile the gradient correction applyed in QZ. It is possible?

**Comment by cagnulein** [comment]
> BTW my expectation is that on the Inclination tile QZ shows the correct gradient received from the app to match what is on app screen and within the same tile the gradient correction applyed in QZ. It is possible?

i will think about it
