### ISSUE TITLE
Speed Changing On Hill With Constant Gear & Cadence

### ISSUE THREAD

**Issue by Tazfiend** [cagnulein/qdomyos-zwift#2853]
As described on Facebook: when climbing a slope the speed would drop while gear, cadence and power output remained constant. (I also discovered that I shouldn't lock my phone mid-ride, as that seemed to drop the connection to the MyWhoosh app on the PC). 
[debug-Sat_Nov_30_19_59_35_2024.log](https://github.com/user-attachments/files/17969116/debug-Sat_Nov_30_19_59_35_2024.log)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
Log checked : i suggest to remove the ftms bike setting in the bike options
(set it to disabled) and press OK and restart qz and give it another try

In this way it will use the native wahoo protocol
Let me know!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 1 dic 2024 alle 14:53 Tazfiend ***@***.***> ha
scritto:

**Comment by Tazfiend** [comment]
The behaviour is the same - changing gear on QZ changes the power output for the cadence, but the road speed in MyWhoosh is related to power and slope, not gear and cadence. So in the same gear I was doing 5kmh and 50kmh, depending on the slope. 
[debug-Sun_Dec_1_18_50_54_2024.log](https://github.com/user-attachments/files/17970226/debug-Sun_Dec_1_18_50_54_2024.log)

**Comment by cagnulein** [comment]
@Tazfiend I don't understand: a couple of questions to clarify it

1. Do you feel the hills on qz?
2. Do you feel the gears on qz?

If they are both yes and, like you said, the power is changing when you change gears on qz, the speed must reflect on mywhoosh otherwise it's a mywhoosh bug (but I don't think so because a lot of users are using your same setup without issues)

How do you pair qz and mywhoosh in its pairing window?

Make a screenshot, and also if you can make me a video of the fact that the power is increasing but the speed doesn't change on mywhoosh. If so we should send them on their support

**Comment by Tazfiend** [comment]
![20241201_192043](https://github.com/user-attachments/assets/30684dc2-e33a-4387-be52-f5612a830cca)
The power is not increasing. The power stays the same, for the same pedal cadence. But the road speed changes as the slope changed. So, in gear 14 at around 85rpm I was producing around 220 watts. (If I changed to gear 15 I produced more power for the same cadence). But going downhill I was doing 50+kph, and going uphill I dropped to 5kph, still in gear 14.

**Comment by Tazfiend** [comment]
It's like being in ERG mode, where the gears change to target power instead of changing the wheel/road speed.

**Comment by cagnulein** [comment]
> The power is not increasing. The power stays the same, for the same pedal cadence.

hah ok frm this phrase i got the opposite "changing gear on QZ changes the power output for the cadence, but the road speed in MyWhoosh"

i double checked the log and i suggested to remove the FTMS bike setting but in the log is still there. Are you aware of this?
Let me know!

**Comment by Tazfiend** [comment]
Damn! I definitely disabled it, but you're right. I've disabled it again, and I'll try again.

**Comment by cagnulein** [comment]
ok be sure that it doesn't write it back automatically. it shouldn't
Let me know!

**Comment by Tazfiend** [comment]
I have tried three times. It disabled, but as soon as I connect to the bike it shows enabled again. Am I changing the correct setting?
![Screenshot_20241202_110424](https://github.com/user-attachments/assets/030b5255-c458-41ff-83a4-1ed24e95b428)

**Comment by cagnulein** [comment]
i guess i got it, use the nightly build here https://github.com/cagnulein/qdomyos-zwift/actions/runs/12110466145/artifacts/2259113320

it will be on the store otherwise in 5 days if you want to wait

Google is very slow in these days, reviewing the app on the store, even the beta ones. For this reason, in order to check right now if the patch that I did is right, you can use the android build in the link (check at the bottom of the page in about 1 hour). In order to test it you need first to remove the current QZ version on your phone, install the one that you downloaded.
This version is a 15 minutes trial (you can restart it as many times as you want) and I can unlock it if you want, send me an email to roberto.viola83@gmail.com mentioning this ticket and that you are on android.
Let me know if you have any questions

**Comment by Tazfiend** [comment]
That seems to have fixed it. 👍🏻

I've only tried a short ride in MyWhoosh, but gear seems connected to road speed, I feel it getting harder on the hills, and power varies with the slope if I maintain cadence in the same gear. 👍🏻

**Comment by cagnulein** [comment]
amazing! remember to send me the email if you want to unlock it!
