### ISSUE TITLE
[BUG] No resistance change during Zwift segment (i. e. Jarvis KOM)

### ISSUE THREAD

**Issue by seruemme** [cagnulein/qdomyos-zwift#2869]
Describe the bug
In some situations the resistance from my Tacx Flus s is stuck. I saw this today when riding on Zwift on a defined segment (Jarvis KOM). Before that segment the resistance changed due to the course (more resistance when climbing, less on descends) and as well by vitual shifting on the QZ app. During that segment I pedaled constantly at 80 RPM and had to bring like 200 Watts. Regardless of the topography or the QZ settings. Making a break and pressing pause did not do any good. After that segment both worked fine again.

Expected behavior
The resistance shall change due to the topography (ascend, descend) and as well due to virtual shoifting.

Screenshots
![image](https://github.com/user-attachments/assets/47198561-e80a-49e6-b7ee-0c91a8b5cb57)

Smartrainer
 - Tacx Flux s

Smartphones
 - QZ running on: Honor 10
 -- OS: Android 10
 - Zwift running on: iPhone SE
 -- iOS 18.11 

Debug log
[debug-Tue_Dec_3_08_55_10_2024.zip](https://github.com/user-attachments/files/17998832/debug-Tue_Dec_3_08_55_10_2024.zip)

**Comment by cagnulein** [comment]
Thanks I will check it tomorrow

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 3 dic 2024 alle 21:48 seruemme ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
could be inside this time frame

Di. Dez. 3 09:19:29 2024 1733213969443 Debug: ../src/characteristics/characteristicwriteprocessor.cpp virtual void CharacteristicWriteProcessor::changeSlope(int16_t, uint8_t, uint8_t) "calculated erg grade -0.09"
Di. Dez. 3 09:24:22 2024 1733214262324 Debug: ../src/characteristics/characteristicwriteprocessor.cpp virtual void CharacteristicWriteProcessor::changeSlope(int16_t, uint8_t, uint8_t) "new requested resistance zwift erg grade -9 enabled \u0001"

I see a hole of 5 minutes. In case, it's a zwift bug because it's getting my data but it's not updating the slope. Then it restarted automatically. Maybe you can try to redo the same circuit to check if it's a determistic error

Let me know

**Comment by cagnulein** [comment]
@seruemme Any news?
