### ISSUE TITLE
[BUG] Automatic reconnect of QZ in Rouvy

### ISSUE THREAD

**Issue by satchafunkilus** [cagnulein/qdomyos-zwift#2894]
**Describe the bug**
Rouvy does not automatically reconnect to QZ if it has been connected in a previous session. Instead, QZ appears twice in the available devices. The "old" instance, which is showing as "Connecting....", but will never connect, and the new one. Both are named exactly the same. You need to manually switch all devices from the old to the new instance every time in order to get a connection.

**To Reproduce**
1. Start Rouvy
2. Connect QZ as trainer (HR, cadence, etc. will automatically switch to QZ)
3. Leave Rouvy app
4. Restart Rouvy
5. See error (QZ will not reconnect)
6. Manually remove the old QZ from trainer, cadence, HR, etc.
7. Connect to new QZ as trainer (HR, cadence, etc. will automatically switch to QZ)

**Expected behavior**
Rouvy should automatically reconnect to QZ. When connecting Rouvy to the trainer directly, the reconnection works.

**Comment by cagnulein** [comment]
yes it's a rouvy issue and it's not fixable from qz. rouvy uses the mac address to identify the devices. since ios and android both randomize the mac address due to privacy laws, every time qz creates the virtual interface, the mac address changes. there are custom flavour of android that allows you to remove this limitation.

you don't have this if you run qz from raspberry, mac or pc

**Comment by mrjcleaver** [comment]
If you are using an old phone that doesn't need the privacy of random mac addresses, you can probably disable randomization.

https://www.howtogeek.com/722653/how-to-disable-random-wi-fi-mac-address-on-android/
