### ISSUE TITLE
Fitmetria Fanfit

### ISSUE THREAD

**Issue by cagnulein** [cagnulein/qdomyos-zwift#505]

**Comment by cagnulein** [comment]
[Uploading basic_example.py.zip…]()

**Comment by marcelomanzo** [comment]
Todo:

Rename Fitmetria Fanfit to Fitmetria Fitfan

Always On
1) < 0 goes to 255
2) > 10 shold go to 0 (careful do not send > 1023 to the fan)
3) Rename Always on to Manual
4) Sometimes one tap increases / decreases 2

Heart:
1) Use scale of 10 steps, instead of 100 steps

Wind: 
1) Remove it for the MVP

**Comment by cagnulein** [comment]
Can you please do the following changes?

1) + / - buttons goes from 0 - 10 (it's impossible to use from 0 - 256)
If gets into 10 and the user press +, goes back to 0
If its 0, user press -, goes to 10

2) Min and Max in the settings are not being scaled.

Basically, If I set from 20 - 80 in the settings

what it does now is that if I set the tile value to 15, it sends 20 and if I set the tile to 90 it sends 80

What I am looking for is a proportion.

You can use this C++ function:

long map(long x, long in_min, long in_max, long out_min, long out_max) {
  return (x - in_min) * (out_max - out_min) / (in_max - in_min) + out_min;
}

so if you call
map(7 value that I set in the tile, 
    0 min tile,
	10 max tile,
	200 (20 from min from the settings * 10),
	800 (80 from max from the settings * 10)
	
it will send return 620 (convert to int), that is the value that you send to the fan.
