### ISSUE TITLE
[REQ] Build environment setup instructions

### ISSUE THREAD

**Issue by rjbutler** [cagnulein/qdomyos-zwift#513]
It would be helpful to have a document describing the build environment setup.  What's needed other than the QZ repo (which QT components), what to replace/symlink in QT, anything else that's needed to successfully setup and build.

**Comment by cagnulein** [comment]
@rjbutler did you read this https://github.com/cagnulein/qdomyos-zwift/blob/master/docs/10_Installation.md ?
the qhttpserver is described more here https://github.com/cagnulein/qdomyos-zwift/pull/252
Feel free to modify the document with a pull request in order to match up the right steps
Let me know

P.S. didn't you receive the build yet via test flight?

**Comment by rjbutler** [comment]
I did look at the installation file, but at least for Mac it looks like it more how to run QZ on Mac rather than how to build.   Thanks for the link to #252, that looks like what I need.

I didn’t receive the build via test flight, I’m still on 2.8 (108).

**Comment by cagnulein** [comment]
> I did look at the installation file, but at least for Mac it looks like it more how to run QZ on Mac rather than how to build ios. Thanks for the link to #252, that looks like what I need.

MacOS build is the same as iOS for the QT :)

> 
> I didn’t receive the build via test flight, I’m still on 2.8 (108).

i tried to send you it again now. Let me know if it's better

**Comment by cagnulein** [comment]
did you achieve this @rjbutler ?

**Comment by rjbutler** [comment]
@cagnulein yeah, I think I've got it now.  Thanks.
