### ISSUE TITLE
SynchronAction XT900

### ISSUE THREAD

**Issue by bonovoxpride** [cagnulein/qdomyos-zwift#53]

**Comment by cagnulein** [comment]
@bonovoxpride welcome aboard!

In order to manage your TM you need to follow these steps:

1. you need to become developer on your phone https://wccftech.com/how-to/how-to-enable-developer-options-on-android-10-tutorial/
2. Go to Settings
3. Go into developer options
4. Enable the option Enable Bluetooth HCI snoop log
5. restart your phone
6. open the TRX app and play with it collecting inclination and speed
7. Disable the option Enable Bluetooth HCI snoop log
8. on your phone you should have a file called btsnoop_hci.log
9. attach the log file here with a short description of the steps you did in the TRX app when you used it

Let me know if something is unclear

**Comment by bonovoxpride** [comment]
arrivato al punto 5, ora l'app TRX cos è?

**Comment by cagnulein** [comment]
scusami errore di copia incolla, TRX è l'app che usi sul telefono normalmente per vedere il tuo tapis.

Let's back to english now ;)

**Comment by bonovoxpride** [comment]
ok, then I have to use the tablet. I update you thanks

**Comment by cagnulein** [comment]
@bonovoxpride are you still interested on this?
