### ISSUE TITLE
Telemetry Loss on Cadence < 50 [BUG]

### ISSUE THREAD

**Issue by BrianRVT** [cagnulein/qdomyos-zwift#612]
[debug-Sat_Jan_22_11_31_00_2022.zip](https://github.com/cagnulein/qdomyos-zwift/files/7921445/debug-Sat_Jan_22_11_31_00_2022.zip)

If cadence drops under 50 rpm all telemetry zeros out.  Happens on a Flywheel IC5.  Recreated on a Pixel 6 and Samsung S2 tablet.

**Comment by cagnulein** [comment]
Hi @BrianRVT  i checked the log and the issue comes directly from your bike. infact i added in the past the setting ""Samples Filter:" in the flywheel section in order to filter these kind of wrong frames. Try to play with this. It's just a filter, so with high value, you will see a more stable metrics, or with 0, there is no filter at all.
Let me know if you have any further questions
