### ISSUE TITLE
QZ Debug Log Analyzer

### ISSUE THREAD

**Issue by cagnulein** [cagnulein/qdomyos-zwift#694]
I was thinking about some web tool to analyze the logs like https://www.elastic.co/ or splunk

Do you have some ideas about this?
@p3g4asus 
@Zutroy23

**Comment by Zutroy23** [comment]
I've never used either of those tools, so unfortunately I'm not much help with this.  It didn't take much effort to pull out what I wanted from the log files using Notepad++, copied the rows I wanted into Excel, then loaded that file into my BI tool (Tibco Spotfire) on my work pc.  Not elegant, but it works.

**Comment by cagnulein** [comment]
yes i'm doing something similar @Zutroy23 but i would like to automatize the process. i will keep you posted on this

**Comment by cagnulein** [comment]
mmm this one it's not so bad https://github.com/variar/klogg but it's not what i wanted

**Comment by AngryAznMn** [comment]
Are you saying you need something else from me?
________________________________

**Comment by cagnulein** [comment]
@AngryAznMn yes but you have to answer here https://github.com/cagnulein/qdomyos-zwift/issues/704

**Comment by cagnulein** [comment]
https://github.com/RunaCapital/awesome-oss-alternatives

**Comment by eMadman** [comment]
Out of curiosity, do you have any grok patterns already that I can use as a start point for this?  Pulling the log file into elastic search via manual upload... it needs a pattern to match to for analysis.... for now, I'm playing around with it on a docker-compose installation on a VM

![image](https://user-images.githubusercontent.com/24726844/159291282-80470c50-a2dd-4858-9659-591684295ce4.png)

**Comment by eMadman** [comment]
I'm wondering if structured data in the logs is necessary for ES to know what to do with it.  Seems to be getting stuck here regardless of what I input for the override settings
![image](https://user-images.githubusercontent.com/24726844/159332527-c8d70c2c-f065-43f8-8282-5100a1f9f19c.png)

Different log file, different  error... this is still before any filtering/mapping.  Same error if I upload only 1000 lines... I'll have to come back to it later.

Compared to other log parsers I fiddled around with over the weekend, I like that ES allows manual uploading of the log files.  Many of the others don't seem to accept individual logs like this.  InfluxDB and others require a log collector installed to send data over.  Graylog's docker-compose instructions aren't working for me as well.  Seems to be a version # issue on the first line of the docker-compose... which is also weird because I should have the latest on my Ubuntu VM

**Comment by cagnulein** [comment]
Mmm so weird, with splunk I was able to parse the files but I didn't try to run it locally (I don't know if it can run for free also)

Maybe another idea will be a better organisation of the qz logs directly from qz itself. Maybe a json formatting will do the job?

**Comment by eMadman** [comment]
I think with json formatting, we'd have a lot of flexibility to pick for visualization and parsing.  It should also eliminate the need for regex/grok

**Comment by cagnulein** [comment]
@eMadman I can add easily a Json formatting for each line tagging timestamp, code line, file and message but I don't know how it will be useful since the precious informations will remains in the message tag. What do you think?

**Comment by cagnulein** [comment]
@eMadman i'm using klogg and i'm quite satisfied with it, give it a try

**Comment by eMadman** [comment]
Will try Klogg!

RE: JSON - it'll likely be limited in value to being able to filter against by time, log level, and the file in code being executed (I'm assuming it can be split out along those lines) ....message contents would still be the wildcard 

The file structure is predictable... I might actually be able to do something to quickly parse along these lines using find/left/right formulas in a spreadsheet
