### ISSUE TITLE
[BUG] Bowflex BXT216 Treadmill

### ISSUE THREAD

**Issue by KurtRamsey** [cagnulein/qdomyos-zwift#712]
When the treadmill is paused, stopped, and even turned off the qzdomyos app broadcasts the last known Speed value. It will continue to do so until a new speed is registered.

[debug-Fri_Mar_4_19_17_33_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/8189428/debug-Fri_Mar_4_19_17_33_2022.log)

**Comment by cagnulein** [comment]
Hi @KurtRamsey the log is empty :)
Anyway for the disconnection i can put the speed to 0 when it happens, for the paused and stopped i need a debug log because probably the treadmill is keeping sending the last speed value but also along with a state byte that tells to the app that the treadmill is paused. let me know

**Comment by KurtRamsey** [comment]
[debug-Fri_Mar_4_19_19_11_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/8190584/debug-Fri_Mar_4_19_19_11_2022.log)

**Comment by cagnulein** [comment]
@KurtRamsey any news about this?

**Comment by KurtRamsey** [comment]
Using Android qz, the speed correctly drops to 0.0 when the workout is fully stopped. However, when 'paused' qz still shows the last known speed value.

**Comment by cagnulein** [comment]
Hi @KurtRamsey could you please generate me a debug log with this issue? Thanks
