### ISSUE TITLE
Chart for echelon-peloton resistance conversion

### ISSUE THREAD

**Issue by cagnulein** [cagnulein/qdomyos-zwift#78]
![echelon-peloton-resistance conversion](https://user-images.githubusercontent.com/48216/102335878-c2255880-3f90-11eb-80ed-012ab0de24a0.jpg)

add an option to enable it

**Comment by marklogan17** [comment]
I could see other bikes wanting this too.  So maybe rather than displaying the chart, its a preference to turn on and then in the resistance field it shows the Peleton resistance rather than the echelon one.  I'm sure we could create a nice linear algorithm to convert.  We would certainly get lots of feedback :)

**Comment by cagnulein** [comment]
[echelon peloton resistance.xlsx](https://github.com/cagnulein/qdomyos-zwift/files/5703220/echelon.peloton.resistance.xlsx)
i created the formula here, i'm adding to the source code now
