### ISSUE TITLE
Certain Echelon Stats Dont Show For Most of Exercise

### ISSUE THREAD

**Issue by saucedrip** [cagnulein/qdomyos-zwift#801]
[debug-Wed_May_4_15_44_44_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/8626866/debug-Wed_May_4_15_44_44_2022.log)
hi Roberto,

Echelon stats like average speed and odometer don’t begin to show values until on average 25 mins into workout.

**Comment by cagnulein** [comment]
hi @saucedrip in this log there is no connection at all with your bike, maybe you uploaded the wrong file? Let me know

**Comment by saucedrip** [comment]
Hi @cagnulein 
I might have.  Looks like there was three and thought I uploaded the biggest.  I’ll upload all just in case.  If none show a connection, I can recreate today.

**Comment by cagnulein** [comment]
[GitHub Qdom Debug Logs.zip](https://github.com/cagnulein/qdomyos-zwift/files/8637824/GitHub.Qdom.Debug.Logs.zip)

**Comment by cagnulein** [comment]
@saucedrip i checked your log: the good news is the bluetooth connection with the bike is perfect.
The issue is, for example in the file debug-Wed_May_4_13_41_17_2022 2, i saw cadence only for 3 minutes. Is it what you also saw? If so, is 100% an hardware issue unfortunately. You should contact echelon for a replace. I don't remeber what was the output of the echelon app test

**Comment by cagnulein** [comment]
@saucedrip any news?

**Comment by saucedrip** [comment]
Hi Roberto,
Have not heard from Echelon.  Let me follow up with them.  In the bug log was there a certain set of code that pointed to a hardware issue?  I’ve managed to trigger the speed etc earlier in my rides inconsistently lately.

Thanks Mat

**Comment by cagnulein** [comment]
Yes @saucedrip it seems an hardware issue from the debug log. Did you try on the echelon app?

**Comment by cagnulein** [comment]
@saucedrip any news?
