### ISSUE TITLE
[BUG] TACX NEO2T on Peloton with QDOMYOSZWIFT resistance issues

### ISSUE THREAD

**Issue by AlexanderMakowski** [cagnulein/qdomyos-zwift#878]
**Describe the bug**
The system changes resistance inconsistently with target after recent updates. Attempt to adjust auto resistance with tweak settings causes resistance to plummet. Target read correctly but resistance not. 

**To Reproduce**
1. Go to peloton app and start a ride. Start Qdomyoszwift auto follow resistance upon prompt. When resistance doesn't match target attempt to adjust target resistance by %. Observe changes in actual resistance either above or way below actual target 
2. Click on 

**Expected behavior**
Resistance as expected as it was before updates.

**Screenshots**

**Desktop (please complete the following information):*
iPad with iOS runs peloton app as suggested

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Pro
 - OS: ios 15.6
 

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
[debug-Mon_Aug_1_21_34_03_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/9239116/debug-Mon_Aug_1_21_34_03_2022.log)

  
**Additional context**

**Comment by cagnulein** [comment]
@AlexanderMakowski thanks, I'm trying to understand what has changed. I would like first to explain how does it works and then I would like to ask you something.

Actually I'm receiving the resistance request from the peloton workout: i'm translating it to inclination % on your tacx since your device doesn't have the concept of resistance.

The algorithm of resistance to % it's very simple. 20 peloton resistance is a 2%, 40 peloton resistance is 4% and so on. I checked git and this algorithm has not been changed during the last update.

Let's talk instead of the peloton resistance showed in the tile. This one, instead, in the last version has been modified to better match the real peloton resistance level to your tacx with this commit https://github.com/cagnulein/qdomyos-zwift/commit/4a47c96e2707b050a709a268a8a0a7619cee9dad

So maybe that's the reason why you're seeing a difference. So now your current peloton resistance doesn't match anymore the target one, isn't it?
If this is the issue, actually is not an issue :) or in better words, I just improved the calculation so maybe now it's time to have a better match of the peloton resistance to % algorithm. What do you think? If you agree we need a translation table of the peloton resistance to the %.

The actual algorithm the calculate the realtime peloton resistance is using the cadence and power.

Sorry for my bad english but I'm italian. I hope it will be understandable for you

**Comment by cagnulein** [comment]
I saw another issue also in the log, and maybe that's the one that you were reering to. Using the peloton resistance minus button, the resistance went to 0 for a moment. I'm checking this

**Comment by cagnulein** [comment]
@AlexanderMakowski did you try to use the gear tile instead of the target resistance minus/plus button? Let me know

**Comment by AlexanderMakowski** [comment]
I am not aware of the gear tile.
I will find it and try to use it today and get back to you.

Whatever one you advise, I will use tp modify resistance of create an offset that works for me.

Thanks for looking into this.
If there is any undesired behavior, it appears it would only be the modification of resistance during riding. Perhaps even just some guidance from you, I could learn your software better, instead of asking for changes.

Again thanks for the prompt response and I'm happy to help test or participate.

Best,
Alex

Alexander J Makowski, Ph.D.

**Comment by cagnulein** [comment]
Perfect! I'm here when you will try the gear tile! Have a nice day!

**Comment by AlexanderMakowski** [comment]
Thank you Roberto!
The Gears Tile worked spectacularly for adjusting resistance today and will help me dial in a good workout .
Your app is really helping achieve my goals.

Thanks for guiding me.

Warmly,
Alex

Alexander J Makowski, Ph.D.

**Comment by cagnulein** [comment]
great! @AlexanderMakowski let me know if I can do something else to improve the overall experience 
actually i'm at the hospital with my wife that she is pregnant so my answers should be delayed :)

**Comment by AlexanderMakowski** [comment]
I hope everything goes smoothly for you and your wife Roberto!



Alexander J Makowski, Ph.D.
